// ============================================================
//  NINH BÌNH AI — Ăn vặt
//  File: anvat.js
// ============================================================

const SNACKS = [
  {
    name: 'Kem Xôi Thanh Hằng',
    nameEn: 'Thanh Hang Sticky Rice Ice Cream',
    lat: 20.2572, lng: 105.9705,
    color: '#ec4899', type: 'snack', priority: true,
    location: '36 Cù Chính Lan (Phố 8), Tân Thành, Ninh Bình',
    locationEn: '36 Cu Chinh Lan (Pho 8), Tan Thanh, Ninh Binh',
    price: '15.000 – 40.000đ/cốc', priceEn: '15,000 – 40,000 VND/cup',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ăn vặt kinh điển và nổi tiếng nhất Ninh Bình. Kem xôi dẻo thơm, kem béo ngậy, thường ăn kèm bánh đa giòn. Luôn đông khách từ sáng đến tối muộn.',
    noteEn: 'The most legendary sticky rice ice cream in Ninh Binh. Creamy, fragrant and addictive. Often paired with crispy rice crackers.',
  },
  {
    name: 'Thịt Xiên Nướng Đức Trọc',
    nameEn: 'Duc Troc Grilled Skewers',
    lat: 20.2605, lng: 105.9750,
    color: '#ec4899', type: 'snack', priority: true,
    location: '52 Hoàng Hoa Thám, Vân Giang, TP. Ninh Bình',
    locationEn: '52 Hoang Hoa Tham Street, Van Giang, Ninh Binh City',
    price: '5.000 – 20.000đ/xiên', priceEn: '5,000 – 20,000 VND/skewer',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Thịt xiên nướng nổi tiếng giới trẻ Ninh Bình. Thịt ướp đậm đà, nướng thơm lừng. Giá rẻ, ăn vặt rất hợp.',
    noteEn: 'Popular grilled skewers loved by local youth. Well-marinated meat, fragrant and affordable.',
  },
  {
    name: 'Chè Bưởi An Giang',
    nameEn: 'An Giang Grapefruit Sweet Soup',
    lat: 20.2560, lng: 105.9720,
    color: '#ec4899', type: 'snack', priority: true,
    location: '14 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: '14 Luong Van Tuy Street, Tan Thanh, Ninh Binh',
    price: '15.000 – 25.000đ', priceEn: '15,000 – 25,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Chè bưởi chuẩn vị, cùi bưởi giòn, đậu xanh mềm, nước cốt dừa béo ngậy. Món ăn vặt mát lạnh được khen ngon nhất Ninh Bình.',
    noteEn: 'Grapefruit sweet soup with crunchy pomelo, soft mung beans and rich coconut milk. Highly recommended.',
  },
  {
    name: 'Bánh Mì Cố Đô',
    nameEn: 'Co Do Banh Mi',
    lat: 20.2555, lng: 105.9725,
    color: '#ec4899', type: 'snack', priority: true,
    location: '117 Lương Văn Tụy, Hoa Lư, Ninh Bình',
    locationEn: '117 Luong Van Tuy Street, Hoa Lu, Ninh Binh',
    price: '20.000 – 35.000đ/ổ', priceEn: '20,000 – 35,000 VND',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Bánh mì nóng giòn, nhân đầy ú ụ. Có chương trình tặng nước đậu miễn phí. Được giới trẻ và du khách yêu thích.',
    noteEn: 'Crispy hot baguette with generous fillings. Often offers free soy milk. Popular among locals and tourists.',
  },
  {
    name: 'Bánh Mì Chảo Bánh Mì Giòn',
    nameEn: 'Banh Mi Chao - Banh Mi Gion',
    lat: 20.2568, lng: 105.9728,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Số 7, Ngõ 43 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: 'No. 7, Alley 43 Luong Van Tuy, Tan Thanh, Ninh Binh',
    price: '15.000 – 45.000đ', priceEn: '15,000 – 45,000 VND',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Bánh mì chảo nóng giòn nổi tiếng đường Lương Văn Tụy. Ăn kèm pate, trứng, xúc xích, chả... rất hợp ăn sáng hoặc ăn vặt muộn.',
    noteEn: 'Famous hot crispy pan-fried banh mi. Served with pate, egg, sausage, etc. Great for breakfast or late-night snack.',
  },
  {
    name: 'Nem Nướng Nha Trang',
    nameEn: 'Nha Trang Grilled Spring Rolls',
    lat: 20.2630, lng: 105.9685,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Công viên Thúy Sơn, đường Lê Đại Hành, TP. Ninh Bình',
    locationEn: 'Thuy Son Park, Le Dai Hanh Street, Ninh Binh City',
    price: '40.000 – 80.000đ/phần', priceEn: '40,000 – 80,000 VND/serving',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Nem nướng kiểu Nha Trang, ăn kèm rau sống, bánh tráng, nước chấm đặc trưng. Không gian công viên thoáng mát.',
    noteEn: 'Nha Trang-style grilled spring rolls with fresh herbs, rice paper and signature dipping sauce. Nice park atmosphere.',
  },
  {
    name: 'Bánh Rán Phố Cổ',
    nameEn: 'Old Quarter Fried Pancakes',
    lat: 20.2492, lng: 105.9772,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Khu ẩm thực đường phố Phố cổ Hoa Lư',
    locationEn: 'Street Food Area, Hoa Lu Old Quarter',
    price: '5.000 – 15.000đ/chiếc', priceEn: '5,000 – 15,000 VND/piece',
    bestTime: 'Buổi tối', bestTimeEn: 'Evening',
    note: 'Bánh rán nóng giòn tan, ăn kèm nước mắm chua ngọt. Món ăn vặt không thể bỏ qua khi dạo Phố cổ về đêm.',
    noteEn: 'Crispy hot fried pancakes with sweet and sour dipping sauce. Must-try street snack in the Old Quarter at night.',
  },
  {
    name: 'Bún Canh Cu Tý',
    nameEn: 'Bun Canh Cu Ty',
    lat: 20.2565, lng: 105.9722,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Số 8, Ngõ 75 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: 'No. 8, Alley 75 Luong Van Tuy, Tan Thanh, Ninh Binh',
    price: '20.000 – 40.000đ/bát', priceEn: '20,000 – 40,000 VND/bowl',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Bún canh đặc sản Ninh Bình với sợi bún to đặc trưng. Nước dùng đậm đà, ăn kèm tiết, chả, tép khô.',
    noteEn: 'Signature Ninh Binh bun canh with extra-large noodles. Rich broth, served with blood cake and dried shrimp.',
  },
  {
    name: 'Bánh Tráng Trộn Phố 8',
    nameEn: 'Pho 8 Rice Paper Salad',
    lat: 20.2570, lng: 105.9710,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Phố 8, khu vực Cù Chính Lan / Lương Văn Tụy, Ninh Bình',
    locationEn: 'Pho 8 area, Cu Chinh Lan / Luong Van Tuy, Ninh Binh',
    price: '15.000 – 35.000đ', priceEn: '15,000 – 35,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Bánh tráng trộn gia vị riêng, giòn dai cay thanh. Món ăn vặt "quốc dân" của người Ninh Bình.',
    noteEn: 'Signature rice paper salad with unique seasoning. A beloved local snack.',
  },
  {
    name: 'PIZZA SEN NINH BÌNH',
    nameEn: 'Pizza Sen Ninh Binh',
    lat: 20.2633694, lng: 105.9677525,
    color: '#f97316', type: 'western', priority: true,
    location: 'Số 1 Đường Trần Hưng Đạo, Phường Hoa Lư, TP. Ninh Bình (Khu vực Phố cổ Hoa Lư)',
    locationEn: 'No. 1 Tran Hung Dao Street, Hoa Lu Ward, Ninh Binh City (Hoa Lu Old Quarter Area)',
    price: '80.000 – 250.000đ', priceEn: '80,000 – 250,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Nằm ngay trong không gian Phố cổ Hoa Lư, quán có không gian đẹp, ấm cúng. Pizza đế giòn thơm, nhiều topping, rất được lòng thực khách và khách du lịch về đêm.',
    noteEn: 'Located right inside Hoa Lu Old Quarter. Cozy atmosphere with crispy-crust pizzas and generous toppings. Highly popular among tourists.',
  },
  {
    name: 'Bún Canh Cô Hoa',
    nameEn: 'Co Hoa Bun Canh',
    lat: 20.2568, lng: 105.9725, // Tọa độ ước tính khu vực ngõ 53 Lương Văn Tụy
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Số 6, Ngõ 53 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 6, Alley 53 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '25.000 – 40.000đ', priceEn: '25,000 – 40,000 VND',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Quán bún canh bình dân quen thuộc của người dân địa phương với hương vị đậm đà truyền thống.',
    noteEn: 'A local budget-friendly bun canh spot serving traditional flavors.',
  },
  {
    name: 'Chạm Buffet',
    nameEn: 'Cham Buffet',
    lat: 20.2545, lng: 105.9655, // Tọa độ ước tính trục đường Lê Thái Tổ
    color: '#ef4444', type: 'asian', priority: true,
    location: '343 Lê Thái Tổ, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '343 Le Thai To Street, Tan Thanh Ward, Ninh Binh City',
    price: '150.000 – 300.000đ', priceEn: '150,000 – 300,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Không gian buffet lẩu nướng hiện đại, menu đa dạng món nhúng và đồ ăn kèm phong phú, thích hợp tụ tập gia đình, bạn bè.',
    noteEn: 'Modern BBQ & Hotpot buffet restaurant with a diverse menu, perfect for gatherings.',
  },
  {
    name: 'Gà Rán Chaewon',
    nameEn: 'Chaewon Korean Fried Chicken',
    lat: 20.2512, lng: 105.9615, // Tọa độ ước tính trục đường Nguyễn Công Trứ
    color: '#ef4444', type: 'asian', priority: false,
    location: '384 Nguyễn Công Trứ, Phường Nam Bình, TP. Ninh Bình',
    locationEn: '384 Nguyen Cong Tru Street, Nam Binh Ward, Ninh Binh City',
    price: '30.000 – 150.000đ', priceEn: '30,000 – 150,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Cơ sở gà rán sốt Hàn Quốc giòn rụm với nhiều hương vị thơm ngon, rất được giới trẻ và học sinh sinh viên yêu thích.',
    noteEn: 'Korean-style sauced fried chicken spot with various delicious flavors, popular among youth.',
  },
  {
    name: 'Nhà Hàng Rơm Vàng',
    nameEn: 'Rom Vang Restaurant',
    lat: 20.2552, lng: 105.9730, // Tọa độ ước tính khu vực 112 Lương Văn Tụy
    color: '#ef4444', type: 'asian', priority: true,
    location: '112 Lương Văn Tụy, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '112 Luong Van Tuy Street, Tan Thanh Ward, Ninh Binh City',
    price: '100.000 – 300.000đ', priceEn: '100,000 – 300,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Nhà hàng ẩm thực đồng quê với không gian ấm cúng, chuyên các món ăn đặc sản dân dã chuẩn vị tinh tế.',
    noteEn: 'Local restaurant serving authentic Vietnamese countryside specialties in a cozy atmosphere.',
  },
  {
    name: 'Bi Béo Quán',
    nameEn: 'Bi Beo Quan',
    lat: 20.2566, lng: 105.9721, // Tọa độ ước tính khu vực Ngõ 75 Lương Văn Tụy
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Số 5, Ngõ 75 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 5, Alley 75 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '20.000 – 60.000đ', priceEn: '20,000 – 60,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Nằm trong ngõ ăn vặt sầm uất, quán phục vụ đa dạng các món ăn nhanh như nem chua rán, khoai tây chiên, chân gà và các thức uống giải nhiệt cho giới trẻ.',
    noteEn: 'Located in a lively food alley, this spot offers popular youth snacks like fried fermented pork rolls, french fries, and chicken feet.',
  },
  {
    name: 'Túi Mơ',
    nameEn: 'Tui Mo Coffee & Tea',
    lat: 20.2530, lng: 105.9765, // Tọa độ ước tính trục đường Bà Triệu
    color: '#ec4899', type: 'snack', priority: true,
    location: '01 Đường Bà Triệu, Phường Vân Giang, TP. Ninh Bình',
    locationEn: '01 Ba Trieu Street, Van Giang Ward, Ninh Binh City',
    price: '25.000 – 50.000đ', priceEn: '25,000 – 50,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Quán nước có không gian decor xinh xắn, nhẹ nhàng. Thực đơn phong phú từ trà sữa, trà trái cây hiện đại đến các món ăn vặt nhẹ, thích hợp để tụ tập tán gẫu.',
    noteEn: 'A charming café with a lovely cozy decor. Offers a trendy selection of milk teas, fruit teas, and light snacks, perfect for friend gatherings.',
  },
  {
    name: 'Viva Mexico - Taco & Grill',
    nameEn: 'Viva Mexico - Taco & Grill',
    lat: 20.2651322, lng: 105.9651667,
    color: '#f97316', type: 'western', priority: true,
    location: '26 Ngõ 8 Đường Tràng An, Tân Thành, TP. Ninh Bình',
    locationEn: '26 Alley 8 Trang An Street, Tan Thanh, Ninh Binh City',
    price: '50.000 – 300.000đ', priceEn: '50,000 – 300,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán chuyên đồ ăn Mexico độc đáo hiếm có tại Ninh Bình với các món Tacos, Burritos, Quesadillas chuẩn vị. Không gian nhỏ nhắn, decor chất và dịch vụ rất thân thiện.',
    noteEn: 'An authentic Mexican restaurant in Ninh Binh serving delicious Tacos, Burritos, and Quesadillas. Charming atmosphere with excellent service.',
  },
  {
    name: 'Pyzzi Pizza Restaurant',
    nameEn: 'Pyzzi Pizza Restaurant',
    lat: 20.2568667, lng: 105.9709161,
    color: '#f97316', type: 'western', priority: false,
    location: '30 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '30 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '40.000 – 200.000đ', priceEn: '40,000 – 200,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Quán pizza quen thuộc với giới trẻ và các gia đình tại trục đường ăn uống Lương Văn Tụy. Phục vụ nhanh chóng, menu đa dạng từ pizza, mỳ Ý đến các món gà rán.',
    noteEn: 'A familiar pizza spot for locals on the lively Luong Van Tuy street. Fast service with a diverse menu including pizza, pasta, and fried chicken.',
  },
  {
    name: 'Pizza Đạt Italy Bar & Restaurant',
    nameEn: 'Pizza Dat Italy Bar & Restaurant',
    lat: 20.2475881, lng: 105.9330287,
    color: '#f97316', type: 'western', priority: true,
    location: 'Thôn Khê Hạ, Xã Ninh Xuân, Huyện Hoa Lư, Ninh Bình',
    locationEn: 'Khe Ha Hamlet, Ninh Xuan Communce, Hoa Lu District, Ninh Binh',
    price: '100.000 – 250.000đ', priceEn: '100,000 – 250,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Nằm gần khu vực các điểm du lịch sinh thái, quán được đánh giá cực cao (4.9 sao) bởi du khách nước ngoài nhờ hương vị Pizza, Mỳ Ý thuần túy chuẩn vị Âu và chủ quán cực kỳ hiếu khách.',
    noteEn: 'Highly rated restaurant near tourist hubs, praised by foreigners for authentic Italian pizzas, pasta, steaks and super welcoming hospitality.',
  },
  {
    name: 'D.Cafe&Bistro - Wood Fired Pizza & Steak',
    nameEn: 'D.Cafe&Bistro - Wood Fired Pizza & Steak',
    lat: 20.2596956, lng: 105.9635048,
    color: '#f97316', type: 'western', priority: true,
    location: '168 Xuân Thành, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '168 Xuan Thanh Street, Tan Thanh Ward, Ninh Binh City',
    price: '60.000 – 350.000đ', priceEn: '60,000 – 350,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Nổi tiếng với dòng Pizza nướng lò củi truyền thống mang lại lớp vỏ giòn rụm và mùi thơm đặc trưng mộc mạc. Không gian kiểu bistro hiện đại, sang trọng thích hợp hẹn hò hoặc tụ họp gia đình.',
    noteEn: 'Famous for authentic wood-fired pizzas with a smoky fragrance and crispy crust. Elegant modern bistro space perfect for dates and family gatherings.',
  },
  {
    name: 'Chả cá Hà Thành',
    nameEn: 'Ha Thanh Grilled Fish',
    lat: 20.259852, lng: 105.969841,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Số 9 Cù Chính Lan, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 9 Cu Chinh Lan Street, Tan Thanh, Ninh Binh City',
    price: '120.000 – 200.000đ/người', priceEn: '120,000 – 200,000 VND/pax',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Chả cá lăng nướng thơm phức trên chảo nóng kèm hành, thì là, ăn với bún và mắm tôm chuẩn vị Hà Nội.',
    noteEn: 'Grilled hemibagrus fish served with dill, spring onions, rice noodles, and shrimp paste.',
  },
  {
    name: 'Choose Hideaway Restaurant',
    nameEn: 'Choose Hideaway Restaurant',
    lat: 20.252433, lng: 105.938501,
    color: '#f97316', type: 'western', priority: true,
    location: 'Thôn Đam Khê Trong, Xã Ninh Hải, Hoa Lư, Ninh Bình',
    locationEn: 'Dam Khe Trong Hamlet, Ninh Hai Commune, Hoa Lu, Ninh Binh',
    price: '80.000 – 250.000đ', priceEn: '80,000 – 250,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Không gian nhà hàng ẩn mình cực chill gần Tam Cốc, nổi tiếng với Pizza, Burgers và các món Âu được khách quốc tế đánh giá rất cao.',
    noteEn: 'A cozy hidden gem near Tam Coc, famous for western dishes, pizzas, and burgers.',
  },
  {
    name: 'Heemang Chicken',
    nameEn: 'Heemang Chicken',
    lat: 20.261895, lng: 105.961314,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Số 10 Ngõ 6 Đường Tràng An, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 10, Alley 6 Trang An Street, Tan Thanh, Ninh Binh City',
    price: '50.000 – 180.000đ', priceEn: '50,000 – 180,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán gà rán và đồ ăn vặt kiểu Hàn Quốc nằm ngay đoạn đầu ngõ vào Tràng An, không gian trẻ trung.',
    noteEn: 'Korean fried chicken and street food shop near Trang An street.',
  },
  {
    name: 'Gà rán Chaewon Trịnh Thị Trang',
    nameEn: 'Chaewon Korean Fried Chicken',
    lat: 20.253341, lng: 105.975412,
    color: '#ef4444', type: 'asian', priority: false,
    location: '46 Tuệ Tĩnh, Phường Nam Thành, TP. Ninh Bình',
    locationEn: '46 Tue Tinh Street, Nam Thanh Ward, Ninh Binh City',
    price: '30.000 – 150.000đ', priceEn: '30,000 – 150,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Thương hiệu gà rán sốt Hàn Quốc quen thuộc của học sinh sinh viên khu vực Nam Thành.',
    noteEn: 'Popular Korean-style sauced fried chicken spot among local students.',
  },
  {
    name: 'Busan Ninh Bình',
    nameEn: 'Busan Korean Food Ninh Binh',
    lat: 20.256158, lng: 105.973415,
    color: '#ef4444', type: 'asian', priority: true,
    location: '06 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '06 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '40.000 – 150.000đ', priceEn: '40,000 – 150,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Chuyên các món ăn đường phố Hàn Quốc như lẩu tokbokki, cơm trộn, mì tương đen ngay trung tâm phố ăn vặt.',
    noteEn: 'Specializing in Korean street food like tokbokki hotpot, bibimbap, and jiajangmyeon.',
  },
  {
    name: 'Blur Chicken',
    nameEn: 'Blur Chicken',
    lat: 20.255912, lng: 105.972104,
    color: '#f97316', type: 'western', priority: false,
    location: 'Ngõ 43 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'Alley 43 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '30.000 – 120.000đ', priceEn: '30,000 – 120,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ăn nhanh chuyên gà rán khoai tây chiên, không gian phù hợp cho nhóm bạn trẻ tụ tập.',
    noteEn: 'Fast food spot focusing on fried chicken and french fries.',
  },
  {
    name: 'KFC Ninh Bình',
    nameEn: 'KFC Ninh Binh',
    lat: 20.252874, lng: 105.974852,
    color: '#f97316', type: 'western', priority: false,
    location: 'Tầng 1 Trung tâm Thương mại Go! Ninh Bình, Đường Trần Nhân Tông, TP. Ninh Bình',
    locationEn: '1st Floor, Go! Mall, Tran Nhan Tong Street, Ninh Binh City',
    price: '40.000 – 150.000đ', priceEn: '40,000 – 150,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Cửa hàng gà rán thức ăn nhanh quốc tế nằm bên trong siêu thị Go! Ninh Bình.',
    noteEn: 'International fast-food chain located inside Go! Mall Ninh Binh.',
  },
  {
    name: 'Jollibee Ninh Bình Trần Hưng Đạo',
    nameEn: 'Jollibee Tran Hung Dao',
    lat: 20.256581, lng: 105.980144,
    color: '#f97316', type: 'western', priority: false,
    location: '02 Trần Hưng Đạo, Phường Đông Thành, TP. Ninh Bình',
    locationEn: '02 Tran Hung Dao Street, Dong Thanh Ward, Ninh Binh City',
    price: '30.000 – 100.000đ', priceEn: '30,000 – 100,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Thương hiệu gà rán, mỳ Ý nổi tiếng phù hợp cho gia đình có trẻ nhỏ, nằm ngay trục đường lớn.',
    noteEn: 'Famous fried chicken and spaghetti fast-food chain, family-friendly.',
  },
  {
    name: 'Ăn vặt bé mỡ (통통이 분식)',
    nameEn: 'Be Mo Korean Snack',
    lat: 20.260451, lng: 105.962115,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Số 33 Ngõ 1 Đường Tràng An, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 33, Alley 1 Trang An Street, Tan Thanh, Ninh Binh City',
    price: '20.000 – 80.000đ', priceEn: '20,000 – 80,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Tiệm ăn vặt nhỏ xinh chuyên các món Hàn tự làm chuẩn vị, giá cả rất học sinh sinh viên.',
    noteEn: 'Charming small eatery serving homemade Korean street food at budget-friendly prices.',
  },
  {
    name: 'Nhà Hàng Hàn Quốc Hong Kang (중화요리 홍강)',
    nameEn: 'Hong Kang Korean Chinese Restaurant',
    lat: 20.259924, lng: 105.966412,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Phố Tân Trung, Đường Lê Thái Tổ, Tân Thành, TP. Ninh Bình',
    locationEn: 'Tan Trung Area, Le Thai To Street, Tan Thanh, Ninh Binh City',
    price: '100.000 – 300.000đ', priceEn: '100,000 – 300,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Nhà hàng chuyên ẩm thực Trung - Hàn (mì tương đen, mì cay hải sản jjamppong, thịt heo chua ngọt탕수육) chuẩn vị do đầu bếp kinh nghiệm chế biến.',
    noteEn: 'Authentic Korean-Chinese restaurant serving Jjajangmyeon, Jjamppong, and Tangsuyuk.',
  },
  {
    name: 'Wallace Ninh Bình',
    nameEn: 'Wallace Burger & Chicken',
    lat: 20.255104, lng: 105.972901,
    color: '#f97316', type: 'western', priority: false,
    location: '136 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '136 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '25.000 – 80.000đ', priceEn: '25,000 – 80,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Thương hiệu đồ ăn nhanh chuyên các dòng hamburger giá rẻ và gà rán giòn rụm.',
    noteEn: 'Fast-food chain specialized in budget-friendly burgers and crispy fried chicken.',
  },
  {
    name: 'Hàn Quốc Quán Ninh Bình (한국관)',
    nameEn: 'Han Quoc Quan Restaurant',
    lat: 20.258752, lng: 105.966814,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Đường Lê Thái Tổ, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Le Thai To Street, Tan Thanh Ward, Ninh Binh City',
    price: '150.000 – 350.000đ', priceEn: '150,000 – 350,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Một trong những nhà hàng đồ nướng và lẩu Hàn Quốc lâu đời, phục vụ đúng phong cách bản xứ với nhiều panchan đi kèm.',
    noteEn: 'Traditional Korean BBQ and hotpot restaurant with authentic flavors and side dishes.',
  },
  {
    name: 'Nhà Hàng Trung Hoa Tương Vận Các',
    nameEn: 'Tuong Van Cac Chinese Restaurant',
    lat: 20.266245, lng: 105.968112,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Đường Tràng An, Phường Hoa Lư, TP. Ninh Bình (Gần khu Phố Cổ)',
    locationEn: 'Trang An Street, Hoa Lu Ward, Ninh Binh City',
    price: '100.000 – 400.000đ', priceEn: '100,000 – 400,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Chuyên đồ ăn Trung Hoa đại lục, các món vịt quay, sủi cảo, đậu sốt Tứ Xuyên đậm đà.',
    noteEn: 'Authentic Chinese restaurant featuring roasted duck, dumplings, and Sichuan tofu.',
  },
  {
    name: 'Bánh Mì Giòn',
    nameEn: 'Banh Mi Gion',
    lat: 20.256801, lng: 105.972822,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Số 7, Ngõ 43 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: 'No. 7, Alley 43 Luong Van Tuy, Tan Thanh, Ninh Binh',
    price: '15.000 – 45.000đ', priceEn: '15,000 – 45,000 VND',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Cơ sở chuyên bánh mì chảo và bánh mì kẹp giòn nóng hổi phục vụ ăn sáng hoặc ăn muộn.',
    noteEn: 'Specializing in crispy baguettes and pan-fried banh mi for breakfast or late snacks.',
  },
  {
    name: 'Bánh mỳ Ngọc',
    nameEn: 'Ngoc Banh Mi',
    lat: 20.258954, lng: 105.974102,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Vân Giang, Phường Vân Giang, TP. Ninh Bình',
    locationEn: 'Van Giang Street, Van Giang Ward, Ninh Binh City',
    price: '15.000 – 30.000đ', priceEn: '15,000 – 30,000 VND',
    bestTime: 'Sáng & Chiều', bestTimeEn: 'Morning & Afternoon',
    note: 'Hàng bánh mì patê truyền thống lâu đời, nước sốt đậm đà, vỏ bánh luôn được nướng nóng giòn trước khi giao.',
    noteEn: 'Long-standing traditional pate banh mi with rich signature sauce.',
  },
  {
    name: 'Bánh Mỳ Đò Quan NĐ - Buffet Xiên',
    nameEn: 'Do Quan Banh Mi & Skewer Buffet',
    lat: 20.251452, lng: 105.976822,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Gần cầu Đò Quan (Khu vực Nam Thành / Vân Giang), TP. Ninh Bình',
    locationEn: 'Near Do Quan bridge area, Ninh Binh City',
    price: '20.000 – 60.000đ', priceEn: '20,000 – 60,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Nổi tiếng với món bánh mì kiểu Nam Định kết hợp quầy buffet xiên bẩn, xiên nướng tự chọn thu hút giới trẻ.',
    noteEn: 'Nam Dinh style banh mi combined with an active self-select skewer buffet.',
  },
  {
    name: 'Bánh mì bơ house',
    nameEn: 'Bo House Banh Mi',
    lat: 20.254821, lng: 105.971552,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Nguyễn Văn Cừ, Tân Thành, TP. Ninh Bình',
    locationEn: 'Nguyen Van Cu Street, Tan Thanh, Ninh Binh City',
    price: '15.000 – 35.000đ', priceEn: '15,000 – 35,000 VND',
    bestTime: 'Sáng & Chiều', bestTimeEn: 'Morning & Afternoon',
    note: 'Tiệm bánh mì hiện đại với các loại nhân đa dạng, đặc biệt là sốt bơ trứng gà tươi tự làm béo ngậy.',
    noteEn: 'Modern banh mi shop featuring rich, creamy homemade egg-butter sauce.',
  },
  {
    name: 'Bánh Mì Siu Bơ',
    nameEn: 'Siu Bo Banh Mi',
    lat: 20.255412, lng: 105.972105,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Trục đường Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '15.000 – 30.000đ', priceEn: '15,000 – 30,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Điểm bán bánh mì giòn rụm với bơ siêu thơm, thích hợp mua mang đi nhanh chóng.',
    noteEn: 'Quick takeaway spot for crispy banh mi with aromatic butter.',
  },
  {
    name: 'Tiệm Bánh Mỳ Hùng',
    nameEn: 'Hung Banh Mi',
    lat: 20.258122, lng: 105.976104,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Lê Hồng Phong, Đông Thành, TP. Ninh Bình',
    locationEn: 'Le Hong Phong Street, Dong Thanh, Ninh Binh City',
    price: '20.000 – 40.000đ', priceEn: '20,000 – 40,000 VND',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Bánh mì thịt nguội, xá xíu truyền thống đầy đặn, phục vụ nhanh nhẹn.',
    noteEn: 'Traditional banh mi filled with char siu pork and cold cuts.',
  },
  {
    name: 'Bi Quán - Đặc sản Đà Nẵng',
    nameEn: 'Bi Quan - Da Nang Specialties',
    lat: 20.257541, lng: 105.971254,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Phố 8, Tân Thành, TP. Ninh Bình',
    locationEn: 'Pho 8, Tan Thanh, Ninh Binh City',
    price: '30.000 – 70.000đ', priceEn: '30,000 – 70,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Mang hương vị miền Trung ra đất cố đô với bánh xèo giòn rụm, nem lụi nướng sả và bún mắm nêm đậm đà.',
    noteEn: 'Serving central Vietnam flavors including crispy Banh Xeo and savory Nem Lui.',
  },
  {
    name: 'Mì Cay SEOUL',
    nameEn: 'Seoul Spicy Noodles',
    lat: 20.255241, lng: 105.973104,
    color: '#ec4899', type: 'snack', priority: true,
    location: '142 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '142 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '35.000 – 70.000đ', priceEn: '35,000 – 70,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Hệ thống mì cay 7 cấp độ nổi tiếng, luôn tấp nập học sinh sinh viên vào buổi tối. Mì nhiều topping hải sản, bò, kim chi.',
    noteEn: 'Famous 7-level Korean spicy noodle soup restaurant, popular with youth.',
  },
  {
    name: 'Bít Tết A Sấm',
    nameEn: 'A Sam Beefsteak',
    lat: 20.259124, lng: 105.968841,
    color: '#f97316', type: 'western', priority: false,
    location: 'Đường Nguyễn Huệ, Phường Nam Bình, TP. Ninh Bình',
    locationEn: 'Nguyen Hue Street, Nam Binh Ward, Ninh Binh City',
    price: '60.000 – 120.000đ/suất', priceEn: '60,000 – 120,000 VND/serving',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Bít tết chảo gang nóng hổi kiểu Việt Nam ăn kèm khoai tây chiên, trứng ốp la và bánh mì giòn.',
    noteEn: 'Vietnamese-style sizzling beefsteak served with fries, fried egg, and baguette.',
  },
  {
    name: 'Ăn Vặt Win Win',
    nameEn: 'Win Win Snack Shop',
    lat: 20.254102, lng: 105.971945,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Gần trường THPT Chuyên Lương Văn Tụy cũ, Tân Thành, TP. Ninh Bình',
    locationEn: 'Near old Luong Van Tuy High School, Tan Thanh, Ninh Binh City',
    price: '15.000 – 50.000đ', priceEn: '15,000 – 50,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Thiên đường ăn vặt với đầy đủ trà sữa, nem chua rán, phô mai que và chân gà sả ớt.',
    noteEn: 'Snack paradise featuring milk tea, fried fermented pork rolls, and cheese sticks.',
  },
  {
    name: 'Bánh tacos nhà labubu',
    nameEn: 'Labubu Tacos House',
    lat: 20.260114, lng: 105.965412,
    color: '#f97316', type: 'western', priority: false,
    location: 'Khu vực Đền Đô / Phố Cổ Hoa Lư, TP. Ninh Bình',
    locationEn: 'Hoa Lu Old Quarter Area, Ninh Binh City',
    price: '30.000 – 60.000đ', priceEn: '30,000 – 60,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quầy đồ ăn bắt trend chuyên phục vụ bánh Tacos vỏ giòn, vỏ mềm với phần nhân biến tấu hợp khẩu vị giới trẻ.',
    noteEn: 'Trendy street-food stall specializing in Mexican tacos adapted to local tastes.',
  },
  {
    name: 'Bún Đậu Cố Đô',
    nameEn: 'Co Do Tofu with Rice Noodles',
    lat: 20.258954, lng: 105.974102,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Số 7 Ngõ 12 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 7, Alley 12 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '30.000 – 60.000đ/mẹt', priceEn: '30,000 – 60,000 VND/set',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Mẹt bún đậu đầy đặn với chả cốm chiên nóng hổi, thịt chân giò luộc, lòng dồi xuất sắc. Không gian sạch sẽ.',
    noteEn: 'Generous Vietnamese tofu & noodle platters with crispy green rice patties and rich shrimp paste.',
  },
  {
    name: 'Bún Đậu Tràng An',
    nameEn: 'Trang An Rice Noodle & Tofu',
    lat: 20.261895, lng: 105.961314,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Đường Tràng An, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Trang An Street, Tan Thanh Ward, Ninh Binh City',
    price: '35.000 – 55.000đ', priceEn: '35,000 – 55,000 VND',
    bestTime: 'Trưa', bestTimeEn: 'Lunch',
    note: 'Vị trí thuận tiện trên trục đường Tràng An, đậu rán giòn tan vỏ ngoài, bên trong mềm béo, mắm tôm pha vừa miệng.',
    noteEn: 'Conveniently located on Trang An street. Features crispy fried tofu and well-balanced dipping sauce.',
  },
  {
    name: 'Bún đậu Bà Dung',
    nameEn: 'Ba Dung Banh Dau',
    lat: 20.253341, lng: 105.975412,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Số 29 Ngõ 106 Lê Hồng Phong, Đông Thành, TP. Ninh Bình',
    locationEn: 'No. 29, Alley 106 Le Hong Phong Street, Dong Thanh, Ninh Binh City',
    price: '30.000 – 50.000đ', priceEn: '30,000 – 50,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Quán bún đậu bình dân quen thuộc của người bản địa, phục vụ nhanh chóng, đồ ăn luôn được chiên mới khi khách gọi.',
    noteEn: 'A local budget-friendly spot where components are freshly fried upon order.',
  },
  {
    name: 'Bếp nhà Hương Béo',
    nameEn: 'Huong Beo Kitchen',
    lat: 20.256158, lng: 105.973415,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Số 41 Ngõ 18 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 41, Alley 18 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '30.000 – 70.000đ', priceEn: '30,000 – 70,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Menu đa dạng các món ăn gia đình, cơm phần và các món trộn kiểu hiện đại phù hợp cho bữa trưa nhanh gọn.',
    noteEn: 'Offers a variety of home-cooked meals, combo rice sets, and modern mixed noodles.',
  },
  {
    name: 'Bún cá Hiền Lâm',
    nameEn: 'Hien Lam Fish Noodles',
    lat: 20.255912, lng: 105.972104,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Số 95 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '95 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '30.000 – 45.000đ/bát', priceEn: '30,000 – 45,000 VND/bowl',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Bún cá rô đồng chiên giòn rụm ngập trong nước dùng ngọt thanh ninh từ xương cá, ăn kèm dọc mùng và rau cải.',
    noteEn: 'Crispy fried fish noodles served in a sweet, clear broth with taro stems.',
  },
  {
    name: 'Bún riêu tóp mỡ Huyền Anh',
    nameEn: 'Huyen Anh Crab Noodles with Pork Cracklings',
    lat: 20.252874, lng: 105.974852,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Số 8 Ngõ 14 Cù Chính Lan, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 8, Alley 14 Cu Chinh Lan Street, Tan Thanh, Ninh Binh City',
    price: '30.000 – 50.000đ/bát', priceEn: '30,000 – 50,000 VND/bowl',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Sự kết hợp hoàn hảo giữa vị chua thanh của riêu cua đồng và tóp mỡ siêu giòn béo ngậy. Quán rất đông khách vào buổi sáng.',
    noteEn: 'Crab noodle soup topped with extra crispy and rich fried pork cracklings.',
  },
  {
    name: 'Riêu Cua Bắp Bò Thành Đạt',
    nameEn: 'Thanh Dat Crab & Beef Noodles',
    lat: 20.256581, lng: 105.980144,
    color: '#ef4444', type: 'asian', priority: false,
    location: '112 Lê Hồng Phong, Đông Thành, TP. Ninh Bình',
    locationEn: '112 Le Hong Phong Street, Dong Thanh, Ninh Binh City',
    price: '35.000 – 60.000đ', priceEn: '35,000 – 60,000 VND',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Nước dùng dậy mùi dấm bỗng thơm nức, thịt bắp bò chần chín tới mềm ngọt cùng giò tai giòn sần sật.',
    noteEn: 'Sour-flavor crab broth served with tender blanched beef shank and ear mushrooms pork rolls.',
  },
  {
    name: 'Bún Riêu Tóp Mỡ Phương Anh',
    nameEn: 'Phuong Anh Crab Noodles',
    lat: 20.260451, lng: 105.962115,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Đường Nguyễn Công Trứ, Phường Nam Bình, TP. Ninh Bình',
    locationEn: 'Nguyen Cong Tru Street, Nam Binh Ward, Ninh Binh City',
    price: '25.000 – 45.000đ', priceEn: '25,000 – 45,000 VND',
    bestTime: 'Sáng', bestTimeEn: 'Morning',
    note: 'Quán ăn sáng bình dân, nước dùng đậm đà hương vị truyền thống, hành phi thơm nức mũi.',
    noteEn: 'Local breakfast venue serving traditional crab noodles with fragrant fried shallots.',
  },
  {
    name: 'Tiệm Trộn - Mỳ Vằn Thắn, Bún, Phở',
    nameEn: 'Tiem Tron - Mixed Noodles Shop',
    lat: 20.259924, lng: 105.966412,
    color: '#ef4444', type: 'asian', priority: false,
    location: '68 Đinh Tiên Hoàng, Phường Đông Thành, TP. Ninh Bình',
    locationEn: '68 Dinh Tien Hoang Street, Dong Thanh Ward, Ninh Binh City',
    price: '35.000 – 50.000đ', priceEn: '35,000 – 50,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Chuyên các loại mỳ trộn, xá xíu, mỳ vằn thắn với nước sốt trộn độc quyền chua ngọt đậm đà, đi kèm bát nước súp ngọt xương.',
    noteEn: 'Specializes in dry mixed noodles with char siu and a savory signature sauce.',
  },
  {
    name: 'Bánh cuốn nóng bà Nhâm',
    nameEn: 'Ba Nham Hot Steamed Rice Rolls',
    lat: 20.255104, lng: 105.972901,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Trục đường Tràng An (Gần ngã tư Lê Thái Tổ), TP. Ninh Bình',
    locationEn: 'Trang An Street (Near Le Thai To Intersection), Ninh Binh City',
    price: '25.000 – 40.000đ', priceEn: '25,000 – 40,000 VND',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Bánh tráng tay mỏng mướt, nhân thịt mộc nhĩ xào đậm đà, ăn kèm chả nướng than hoa thơm lừng và nước chấm ấm nóng.',
    noteEn: 'Freshly steamed rice rolls stuffed with minced pork and wood-ear mushrooms, paired with grilled pork.',
  },
  {
    name: 'Bún cá Cậu Đoành CN Ninh Bình',
    nameEn: 'Cau Doanh Fish Noodles - Ninh Binh Branch',
    lat: 20.258752, lng: 105.966814,
    color: '#ef4444', type: 'asian', priority: true,
    location: '147 Đinh Tiên Hoàng, Phường Đông Thành, TP. Ninh Bình',
    locationEn: '147 Dinh Tien Hoang Street, Dong Thanh Ward, Ninh Binh City',
    price: '35.000 – 55.000đ', priceEn: '35,000 – 55,000 VND',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Thương hiệu bún cá cay Hải Phòng nổi tiếng với cá đồng chiên sâu, chả cá biển dai ngon và nước dùng cay nồng đặc trưng.',
    noteEn: 'Famous spicy fish noodle brand originating from Hai Phong, featuring deeply fried fish cakes.',
  },
  {
    name: 'Đức Trọc Quán',
    nameEn: 'Duc Troc Restaurant',
    lat: 20.266245, lng: 105.968112,
    color: '#ef4444', type: 'asian', priority: false,
    location: '52 Hoàng Hoa Thám, Phường Vân Giang, TP. Ninh Bình',
    locationEn: '52 Hoang Hoa Tham Street, Van Giang Ward, Ninh Binh City',
    price: '40.000 – 150.000đ', priceEn: '40,000 – 150,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Khu ẩm thực chuyên các món nhậu bình dân, đồ nướng và lẩu đuôi bò được cánh mày râu yêu thích.',
    noteEn: 'Local casual diner focusing on budget hotpots, BBQ, and beef dishes.',
  },
  {
    name: 'BÚN ĐẬU PHÚ CỔ',
    nameEn: 'Phu Co Banh Dau',
    lat: 20.256801, lng: 105.972822,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Khu ẩm thực Phố Cổ Hoa Lư, TP. Ninh Bình',
    locationEn: 'Hoa Lu Old Quarter Food Court, Ninh Binh City',
    price: '35.000 – 60.000đ', priceEn: '35,000 – 60,000 VND',
    bestTime: 'Buổi tối', bestTimeEn: 'Evening',
    note: 'Nằm trong không gian lung linh của Phố Cổ về đêm, phục vụ mâm bún đậu đậm chất Kinh Kỳ giữa lòng cố đô.',
    noteEn: 'Located inside the vibrant Hoa Lu Old Quarter, offering typical northern Vietnamese tofu platters.',
  },
  {
    name: 'Bếp của Mỹ Kim',
    nameEn: 'My Kim Kitchen',
    lat: 20.258954, lng: 105.974102,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Ngõ 2 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'Alley 2 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '30.000 – 80.000đ', priceEn: '30,000 – 80,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Tiệm ăn online và offline chuyên các món chân gà sả ớt, miến trộn và các món ăn vặt theo xu hướng của giới trẻ.',
    noteEn: 'Trendy eatery known for chili-lemongrass chicken feet and mixed glass noodles.',
  },
  {
    name: 'Pan Pao - Tiệm bánh bao, trà sữa',
    nameEn: 'Pan Pao - Dumplings & Milk Tea',
    lat: 20.251452, lng: 105.976822,
    color: '#ec4899', type: 'snack', priority: false,
    location: '88 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '88 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '15.000 – 40.000đ', priceEn: '15,000 – 40,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Tiệm ăn vặt hiện đại với bánh bao kim sa heo quay độc đáo ăn kèm trà sữa trân châu tự nấu.',
    noteEn: 'Modern snack shop selling signature savory buns paired with freshly brewed bubble tea.',
  },
  {
    name: 'Chè Thái Hoa Quả - 38 Cù Chính Lan',
    nameEn: 'Thai Fruit Sweet Soup - 38 Cu Chinh Lan',
    lat: 20.2572, lng: 105.9705,
    color: '#ec4899', type: 'snack', priority: true,
    location: '38 Cù Chính Lan (Phố 8), Tân Thành, TP. Ninh Bình',
    locationEn: '38 Cu Chinh Lan Street (Pho 8), Tan Thanh, Ninh Binh City',
    price: '15.000 – 30.000đ', priceEn: '15,000 – 30,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Nằm ngay sát vách Kem xôi Thanh Hằng. Chè Thái ngập tràn sầu riêng tươi, thạch, mít xiêm và nước cốt dừa thơm phức.',
    noteEn: 'Located right next to Thanh Hang Sticky Rice Ice Cream. Rich Thai sweet soup loaded with durian and tropical fruits.',
  },
  {
    name: 'Sữa chua Cô Oanh',
    nameEn: 'Co Oanh Yogurt',
    lat: 20.254821, lng: 105.971552,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Ngõ 3 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'Alley 3 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '10.000 – 25.000đ', priceEn: '10,000 – 25,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Sữa chua dẻo mịn tự làm truyền thống đựng trong hũ thủy tinh, ăn kèm thạch và trân châu cốt dừa ấm nóng.',
    noteEn: 'Homemade creamy yogurt served in traditional glass jars with warm coconut-milk tapioca pearls.',
  },
  {
    name: 'Tiệm Chè Mây',
    nameEn: 'May Dessert Shop',
    lat: 20.255412, lng: 105.972105,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Số 5 Ngõ 43 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 5, Alley 43 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '20.000 – 35.000đ', priceEn: '20,000 – 35,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Tiệm chè mang phong cách hiện đại, menu cập nhật liên tục các món chè dưỡng nhan, chè khoai dẻo Đài Loan.',
    noteEn: 'A modern dessert house serving Taiwanese taro balls and wellness herbal sweet soups.',
  },
  {
    name: 'Tiệm Chè Ngon Phố 8',
    nameEn: 'Pho 8 Delicious Sweet Soup',
    lat: 20.258122, lng: 105.976104,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Khu vực Phố 8 (Cù Chính Lan), Tân Thành, TP. Ninh Bình',
    locationEn: 'Pho 8 Area (Cu Chinh Lan), Tan Thanh, Ninh Binh City',
    price: '15.000 – 30.000đ', priceEn: '15,000 – 30,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Địa điểm tụ tập quen thuộc buổi xế chiều của học sinh với các món chè đỗ đen, chè thập cẩm truyền thống ngọt dịu.',
    noteEn: 'A favorite afternoon gathering spot for locals, offering traditional mixed bean sweet soups.',
  },
  {
    name: 'Chè Tào Phớ Bi Bốp Bông',
    nameEn: 'Bi Bop Bong Tofu Dessert',
    lat: 20.257541, lng: 105.971254,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Số 12 Ngõ 7 Cù Chính Lan, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 12, Alley 7 Cu Chinh Lan Street, Tan Thanh, Ninh Binh City',
    price: '10.000 – 25.000đ', priceEn: '10,000 – 25,000 VND',
    bestTime: 'Trưa & Chiều', bestTimeEn: 'Lunch & Afternoon',
    note: 'Tào phớ mướt mịn, thơm mùi hoa nhài tự nhiên, nước đường thanh mát giải nhiệt mùa hè cực tốt.',
    noteEn: 'Silken tofu pudding infused with natural jasmine fragrance, a perfect summer refresher.',
  },
  {
    name: 'Trang - chè tào phớ',
    nameEn: 'Trang Tofu & Sweet Soup',
    lat: 20.255241, lng: 105.973104,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Gần cổng trường Tiểu học Tân Thành, TP. Ninh Bình',
    locationEn: 'Near Tan Thanh Primary School, Ninh Binh City',
    price: '10.000 – 20.000đ', priceEn: '10,000 – 20,000 VND',
    bestTime: 'Chiều xế', bestTimeEn: 'Late afternoon',
    note: 'Gánh chè tào phớ vỉa hè lâu đời phục vụ học sinh sinh viên, giá siêu rẻ nhưng vị thanh ngon đúng điệu.',
    noteEn: 'Traditional sidewalk tofu pudding stall serving generations of local school children.',
  },
  {
    name: 'Chè Oanh',
    nameEn: 'Oanh Desserts',
    lat: 20.254102, lng: 105.971945,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Nguyễn Huệ, Phường Nam Bình, TP. Ninh Bình',
    locationEn: 'Nguyen Hue Street, Nam Binh Ward, Ninh Binh City',
    price: '15.000 – 30.000đ', priceEn: '15,000 – 30,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán chè gia đình phục vụ các món chè nóng mùa đông và chè đá mùa hè chuẩn vị truyền thống Bắc Bộ.',
    noteEn: 'Family-run dessert shop offering hot sweet soups in winter and iced desserts in summer.',
  },
    {
    name: 'TIỆM CHÈ CÔ DUNG - P. Vân Giang',
    nameEn: 'Co Dung Dessert Shop',
    lat: 20.258412, lng: 105.975104,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Vân Giang, Phường Vân Giang, TP. Ninh Bình',
    locationEn: 'Van Giang Street, Van Giang Ward, Ninh Binh City',
    price: '15.000 – 30.000đ', priceEn: '15,000 – 30,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán chè bình dân lâu đời phục vụ các món chè truyền thống, thạch găng mát rượi tại trung tâm chợ Vân Giang.',
    noteEn: 'Long-standing budget dessert shop serving traditional sweet soups near Van Giang market.',
  },
  {
    name: 'Tiệm Sữa Chua Cô Thúy',
    nameEn: 'Co Thuy Yogurt',
    lat: 20.256124, lng: 105.970841,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Phố 8, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Pho 8, Tan Thanh Ward, Ninh Binh City',
    price: '15.000 – 35.000đ', priceEn: '15,000 – 35,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Sữa chua hũ và sữa chua kẹo mút độc đáo, là điểm hẹn quen thuộc của học sinh trường chuyên cũ.',
    noteEn: 'Charming local yogurt spot popular with generation of local high school students.',
  },
  {
    name: 'Chè Changhi Ninh Bình',
    nameEn: 'Changhi Dessert Ninh Binh',
    lat: 20.256245, lng: 105.974112,
    color: '#ec4899', type: 'snack', priority: false,
    location: '42 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '42 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '25.000 – 45.000đ', priceEn: '25,000 – 45,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Thương hiệu chè ít ngọt hiện đại nổi tiếng với chè thạch thảo mộc, chè dừa dầm và chè sầu thố cẩm.',
    noteEn: 'Modern less-sweet dessert chain known for herbal jellies and durian sweet soups.',
  },
  {
    name: 'Quán xiên chị Huệ',
    nameEn: 'Chi Hue Skewers Shop',
    lat: 20.254102, lng: 105.971945,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Gần trường THCS Lý Tự Trọng, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Near Ly Tu Trong Secondary School, Tan Thanh Ward, Ninh Binh City',
    price: '5.000 – 20.000đ/xiên', priceEn: '5,000 – 20,000 VND/skewer',
    bestTime: 'Chiều xế', bestTimeEn: 'Late afternoon',
    note: 'Thiên đường xiên bẩn, cá viên chiên, nem chua rán cổng trường chuẩn vị học sinh sinh viên.',
    noteEn: 'Classic school-gate street food stall serving various fried skewers.',
  },
  {
    name: 'Buffet Xiên Sạch 50k',
    nameEn: '50k Clean Skewer Buffet',
    lat: 20.255241, lng: 105.973104,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Trục đường Lương Văn Tụy, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Luong Van Tuy Street, Tan Thanh Ward, Ninh Binh City',
    price: '50.000đ/người', priceEn: '50,000 VND/pax',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Mô hình ăn buffet xiên thả ga tự chọn với mức giá cố định cực kỳ hút giới trẻ, đồ ăn sạch sẽ.',
    noteEn: 'All-you-can-eat skewer buffet concept with a flat budget-friendly rate.',
  },
  {
    name: 'Quán Út (Bánh Xèo Nem Lụi)',
    nameEn: 'Ut Quan - Banh Xeo & Nem Lui',
    lat: 20.252874, lng: 105.974852,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Số 10 Ngõ 14 Cù Chính Lan, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 10, Alley 14 Cu Chinh Lan Street, Tan Thanh, Ninh Binh City',
    price: '20.000 – 50.000đ', priceEn: '20,000 – 50,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Bánh xèo vỏ mỏng giòn rụm ngập nhân tôm thịt, nem lụi nướng sả thơm phức cuốn bánh tráng rau sống.',
    noteEn: 'Crispy southern-style pancakes and savory lemongrass grilled pork skewers.',
  },
  {
    name: 'Bún cô Thanh phố 8',
    nameEn: 'Co Thanh Pho 8 Noodles',
    lat: 20.257102, lng: 105.970241,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Ngõ 3 Cù Chính Lan (Phố 8), Tân Thành, TP. Ninh Bình',
    locationEn: 'Alley 3 Cu Chinh Lan Street (Pho 8), Tan Thanh, Ninh Binh City',
    price: '25.000 – 40.000đ/bát', priceEn: '25,000 – 40,000 VND/bowl',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Hàng bún mọc, bún sườn dọn vỉa hè lâu năm, nước dùng trong vắt, ngọt thanh đậm vị truyền thống.',
    noteEn: 'Long-standing sidewalk venue for traditional pork ball and rib noodle soup.',
  },
  {
    name: 'Bún Ốc Bún Canh Cây Cau Quán',
    nameEn: 'Cay Cau - Snail & Thick Noodles Shop',
    lat: 20.259852, lng: 105.969841,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Số 12 Ngõ 75 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 12, Alley 75 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '30.000 – 50.000đ/bát', priceEn: '30,000 – 50,000 VND/bowl',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Địa chỉ bún canh tóp mỡ và bún ốc chuối đậu siêu đông khách, hương vị chua thanh đằm thắm cực kỳ cuốn.',
    noteEn: 'Highly popular local joint for rich snail soup and thick noodles with cracklings.',
  },
  {
    name: 'Ốc Tây Thành',
    nameEn: 'Tay Thanh Snail Shop',
    lat: 20.254821, lng: 105.971552,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Đường Nguyễn Văn Cừ, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Nguyen Van Cu Street, Tan Thanh Ward, Ninh Binh City',
    price: '30.000 – 80.000đ/món', priceEn: '30,000 – 80,000 VND/dish',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Thủ phủ ốc luộc mắm gừng sả và ốc xào me dừa ngập sốt, điểm tụ tập ăn vặt kinh điển về đêm.',
    noteEn: 'A prime gathering spot for boiled and stir-fried snails with ginger-tamarind sauce.',
  },
  {
    name: 'Ốc Cố Đô',
    nameEn: 'Co Do Snails',
    lat: 20.255412, lng: 105.972105,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Ngõ 43 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'Alley 43 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '25.000 – 70.000đ', priceEn: '25,000 – 70,000 VND',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Menu đa dạng các loại ốc biển, móng tay xào tỏi, hàu nướng mỡ hành giá bình dân trong ngõ ăn vặt.',
    noteEn: 'Budget-friendly local alley restaurant specializing in seafood and stir-fried snails.',
  },
  {
    name: 'Ốc Lê Chót Quán',
    nameEn: 'Le Chot Snails Shop',
    lat: 20.258122, lng: 105.976104,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Lê Hồng Phong, Đông Thành, TP. Ninh Bình',
    locationEn: 'Le Hong Phong Street, Dong Thanh, Ninh Binh City',
    price: '30.000 – 90.000đ', priceEn: '30,000 – 90,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ốc xào cay Hải Phòng chuẩn vị, nước sốt sánh mịn đậm đà ăn kèm bánh mì rất hợp.',
    noteEn: 'Hai Phong style spicy stir-fried snails served with rich dipping sauce and bread.',
  },
  {
    name: 'Ốc nhà Na',
    nameEn: 'Na House Snails',
    lat: 20.257541, lng: 105.971254,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Phố Tân An, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Tan An Area, Tan Thanh Ward, Ninh Binh City',
    price: '20.000 – 60.000đ', priceEn: '20,000 – 60,000 VND',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Quán ốc vỉa hè nhỏ xinh, sạch sẽ, nổi tiếng với nước chấm mắm gừng sả pha gia truyền siêu ngon.',
    noteEn: 'Small cozy sidewalk snail stall praised for its brilliant homemade dipping sauce.',
  },
  {
    name: 'Ốc Thu Hà',
    nameEn: 'Thu Ha Snails',
    lat: 20.251452, lng: 105.976822,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Gần khu vực Nam Thành, TP. Ninh Bình',
    locationEn: 'Nam Thanh Area, Ninh Binh City',
    price: '30.000 – 70.000đ', priceEn: '30,000 – 70,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Chuyên phục vụ các loại ốc mít, ốc vặn luộc lá chanh nồng nàn thơm phức ăn kèm sung muối chua ngọt.',
    noteEn: 'Serving traditional boiled freshwater snails alongside sour-sweet salted figs.',
  },
  {
    name: 'Ốc Nhồi Vặn Nhật Dậu',
    nameEn: 'Nhat Dau Fresh Snails',
    lat: 20.260114, lng: 105.965412,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Khu vực Đông Thành (Gần hồ Kỳ Lân), TP. Ninh Bình',
    locationEn: 'Dong Thanh Ward (Near Ky Lan Lake), Ninh Binh City',
    price: '25.000 – 60.000đ', priceEn: '25,000 – 60,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Hàng ốc vặn, ốc nhồi luộc chấm mắm cay xè xộc mũi, rất thích hợp cho những ngày se lạnh.',
    noteEn: 'Local basic spot for hot steamed snails with hot chili fish sauce.',
  },
  {
    name: 'Ốc Nhung',
    nameEn: 'Nhung Snails Shop',
    lat: 20.247588, lng: 105.933028,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Nguyễn Huệ, Phường Nam Bình, TP. Ninh Bình',
    locationEn: 'Nguyen Hue Street, Nam Binh Ward, Ninh Binh City',
    price: '30.000 – 80.000đ', priceEn: '30,000 – 80,000 VND',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Phục vụ nhanh nhẹn, quán có món nem chua rán và trứng cút lộn xào me cực kỳ đắt hàng.',
    noteEn: 'Fast service snack house famous for fried fermented pork and tamarind quail eggs.',
  },
  {
    name: 'ỐC NGON 75 NINH BÌNH',
    nameEn: '75 Delicious Snails',
    lat: 20.256512, lng: 105.972201,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Số 75 Lương Văn Tụy, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '75 Luong Van Tuy Street, Tan Thanh Ward, Ninh Binh City',
    price: '30.000 – 100.000đ', priceEn: '30,000 – 100,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ốc hải sản có tiếng trên phố Lương Văn Tụy, đa dạng cách chế biến từ sốt trứng muối đến nướng phô mai béo ngậy.',
    noteEn: 'Renowned seafood snail restaurant offering rich salted egg yolk and cheese baked toppings.',
  },

  {
    name: 'Bia Tô Nhậu Lai Rai',
    nameEn: 'Bia To Casual Pub',
    lat: 20.263542, lng: 105.969112,
    color: '#3b82f6', type: 'pub', priority: false,
    location: 'Đường Lê Thái Tổ, Phường Đông Thành, TP. Ninh Bình',
    locationEn: 'Le Thai To Street, Dong Thanh Ward, Ninh Binh City',
    price: '100.000 – 250.000đ/người', priceEn: '100,000 – 250,000 VND/pax',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Phong cách uống bia bằng tô độc đáo, menu mồi nhậu phong phú từ trâu gác bếp, mực nướng đến lẩu các loại.',
    noteEn: 'Unique concept serving draft beer in large ceramic bowls alongside versatile vietnamese drinking foods.',
  },
  {
    name: 'Sân Bia Anh EM',
    nameEn: 'Anh Em Beer Garden',
    lat: 20.259124, lng: 105.963504,
    color: '#3b82f6', type: 'pub', priority: false,
    location: 'Khu Đô Thị Xuân Thành, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Xuan Thanh Urban Area, Tan Thanh Ward, Ninh Binh City',
    price: '150.000 – 300.000đ/người', priceEn: '150,000 – 300,000 VND/pax',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Không gian sân vườn rộng rãi, thoáng mát, bia hơi mát lạnh kết hợp các món gà đồi, cá sông tươi sống.',
    noteEn: 'Spacious outdoor beer garden specializing in local free-range chickens and river fishes.',
  },
  {
    name: 'Nhậu Vườn Xoài',
    nameEn: 'Vuon Xoai Drinking Garden',
    lat: 20.265132, lng: 105.965166,
    color: '#3b82f6', type: 'pub', priority: false,
    location: 'Ngõ 8 Đường Tràng An, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Alley 8 Trang An Street, Tan Thanh Ward, Ninh Binh City',
    price: '120.000 – 250.000đ/người', priceEn: '120,000 – 250,000 VND/pax',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán nhậu rợp bóng mát cây xanh nằm trên lối vào khu Tràng An, nổi tiếng với các món dê núi và bê chao.',
    noteEn: 'Shady open-air pub located near Trang An, featuring local mountain goat delicacies.',
  },
  {
    name: 'BIA CÁNH DIỀU',
    nameEn: 'Canh Dieu Beer Hall',
    lat: 20.245124, lng: 105.981254,
    color: '#3b82f6', type: 'pub', priority: true,
    location: 'Chân núi Cánh Diều, Phường Thanh Bình, TP. Ninh Bình',
    locationEn: 'Foot of Canh Dieu Mountain, Thanh Binh Ward, Ninh Binh City',
    price: '100.000 – 200.000đ/người', priceEn: '100,000 – 200,000 VND/pax',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Vị trí đắc địa ngay chân núi Cánh Diều lộng gió, chuyên bia hơi Hà Nội chuẩn vị và đồ nhậu bình dân.',
    noteEn: 'Scenic beer hall under Canh Dieu mountain, iconic for fresh Hanoi draft beer.',
  },
  {
    name: 'Bia Hùng Anh',
    nameEn: 'Hung Anh Beer & Restaurant',
    lat: 20.261124, lng: 105.976541,
    color: '#3b82f6', type: 'pub', priority: false,
    location: 'Đường Đinh Tiên Hoàng, Phường Đông Thành, TP. Ninh Bình',
    locationEn: 'Dinh Tien Hoang Street, Dong Thanh Ward, Ninh Binh City',
    price: '150.000 – 300.000đ/người', priceEn: '150,000 – 300,000 VND/pax',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Nhà hàng bia lớn thích hợp để tổ chức liên hoan, hội họp, thực đơn hải sản tươi sống phong phú.',
    noteEn: 'Large-scale beer restaurant ideal for banquets, gathering, and fresh seafood.',
  },
  {
    name: 'Quán Bia Toàn Kem',
    nameEn: 'Toan Kem Draft Beer',
    lat: 20.252241, lng: 105.973104,
    color: '#3b82f6', type: 'pub', priority: false,
    location: 'Đường Tuệ Tĩnh, Phường Nam Thành, TP. Ninh Bình',
    locationEn: 'Tue Tinh Street, Nam Thanh Ward, Ninh Binh City',
    price: '80.000 – 180.000đ/người', priceEn: '80,000 – 180,000 VND/pax',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán nhậu vỉa hè bình dân cực kỳ đông khách lao động và tài xế, mồi nhậu đơn giản nhưng giá rất rẻ.',
    noteEn: 'Popular street pub with a lively local vibe and highly affordable prices.',
  },
  {
    name: '168 QUÁN BIA - LẨU - NƯỚNG BBQ',
    nameEn: '168 Beer, Hotpot & BBQ',
    lat: 20.259695, lng: 105.963504,
    color: '#3b82f6', type: 'pub', priority: false,
    location: '168 Xuân Thành, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '168 Xuan Thanh Street, Tan Thanh Ward, Ninh Binh City',
    price: '150.000 – 250.000đ/người', priceEn: '150,000 – 250,000 VND/pax',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Tổ hợp lẩu nướng không khói kết hợp bia tươi, nằm trên đại lộ Xuân Thành sầm uất.',
    noteEn: 'Modern smokeless BBQ, hotpot, and fresh beer combo hub on Xuan Thanh avenue.',
  },
  {
    name: 'Bia Vườn Nhãn',
    nameEn: 'Vuon Nhan Beer Garden',
    lat: 20.253645, lng: 105.968112,
    color: '#3b82f6', type: 'pub', priority: false,
    location: 'Phường Nam Bình (Gần ga Ninh Bình mới), TP. Ninh Bình',
    locationEn: 'Nam Binh Ward (Near New Ninh Binh Railway Station), Ninh Binh City',
    price: '100.000 – 220.000đ/người', priceEn: '100,000 – 220,000 VND/pax',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Không gian mát mẻ dưới bóng nhãn lâu năm, mồi nhậu đồng quê trạch đồng chiên, lòng lợn xe điếu.',
    noteEn: 'Cozy rustic drinking spot under long-lived longan trees with traditional countryside sides.',
  },
  {
    name: 'Bia Cát Linh',
    nameEn: 'Cat Linh Beer Station',
    lat: 20.257588, lng: 105.933028,
    color: '#3b82f6', type: 'pub', priority: false,
    location: 'Khu vực ngã ba Chẽ, Xã Ninh Xuân, Huyện Hoa Lư, Ninh Bình',
    locationEn: 'Che Intersection Area, Ninh Xuan, Hoa Lu, Ninh Binh',
    price: '100.000 – 200.000đ/người', priceEn: '100,000 – 200,000 VND/pax',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Điểm dừng chân nhậu lý tưởng cho các hội nhóm sau khi đi trekking, tham quan các hang động Hoa Lư.',
    noteEn: 'A great refreshment pit-stop for tourist groups touring nearby caves.',
  },
  {
    name: 'Chân cánh gà nướng cầu vòm',
    nameEn: 'Cau Vom Grilled Chicken Wings & Feet',
    lat: 20.241512, lng: 105.989241,
    color: '#8b5cf6', type: 'latenight', priority: true,
    location: 'Chân Cầu Vòm, Đường Nguyễn Công Trứ, TP. Ninh Bình',
    locationEn: 'Vom Bridge foot, Nguyen Cong Tru Street, Ninh Binh City',
    price: '15.000 – 60.000đ', priceEn: '15,000 – 60,000 VND',
    bestTime: 'Đêm muộn', bestTimeEn: 'Late night',
    note: 'Quán ăn đêm kinh điển của dân phượt và cú đêm Ninh Bình. Chân cánh gà tẩm ướp mật ong nướng than hoa thơm nức mũi.',
    noteEn: 'An iconic late-night venue known for honey-glazed charcoal grilled chicken parts.',
  },
  {
    name: 'Chân gà nem nướng - đối diện BV 700 giường',
    nameEn: 'Hospital Area Grilled Chicken & Nem',
    lat: 20.231245, lng: 105.979841,
    color: '#8b5cf6', type: 'latenight', priority: false,
    location: 'Đối diện Bệnh viện Đa khoa tỉnh Ninh Bình (BV 700 giường), Phường Nam Thành',
    locationEn: 'Opposite Ninh Binh General Hospital, Nam Thanh Ward',
    price: '10.000 – 50.000đ', priceEn: '10,000 – 50,000 VND',
    bestTime: 'Chiều & Đêm', bestTimeEn: 'Afternoon & Late night',
    note: 'Phục vụ xuyên đêm cho người nhà bệnh nhân và khách ăn muộn, nổi tiếng với nem nướng lụi và chân gà sả ớt.',
    noteEn: 'Open 24/7 catering to hospital visitors and night owls with sweet grilled rolls.',
  },
  {
    name: 'Quán ăn đêm Oanh Tuấn',
    nameEn: 'Oanh Tuan Late Night Diner',
    lat: 20.254124, lng: 105.975241,
    color: '#8b5cf6', type: 'latenight', priority: false,
    location: 'Khu vực ngã tư chợ rồng, Phường Vân Giang, TP. Ninh Bình',
    locationEn: 'Cho Rong Intersection Area, Van Giang Ward, Ninh Binh City',
    price: '30.000 – 100.000đ', priceEn: '30,000 – 100,000 VND',
    bestTime: 'Đêm muộn', bestTimeEn: 'Late night',
    note: 'Chuyên cháo lòng, cháo gà, miến ngan ăn đêm nóng sốt giúp ấm bụng lúc nửa đêm.',
    noteEn: 'Specializes in hot pork organ congee, chicken soup, and glass noodles for late dining.',
  },
  {
    name: 'Quán ăn đêm Cường Tuyết',
    nameEn: 'Cuong Tuyet Late Night Food',
    lat: 20.258954, lng: 105.974102,
    color: '#8b5cf6', type: 'latenight', priority: false,
    location: 'Đường Nguyễn Huệ, Phường Nam Bình, TP. Ninh Bình',
    locationEn: 'Nguyen Hue Street, Nam Binh Ward, Ninh Binh City',
    price: '35.000 – 80.000đ', priceEn: '35,000 – 80,000 VND',
    bestTime: 'Đêm muộn', bestTimeEn: 'Late night',
    note: 'Hàng phở bò bát đá kị rơ và lẩu đuôi bò mini mở tới 1-2h sáng.',
    noteEn: 'Famous for late-night stone bowl beef pho and mini hotpots operating until 2 AM.',
  },
  {
    name: 'Quán Ăn Đêm Khánh Hằng',
    nameEn: 'Khanh Hang Late Night Restaurant',
    lat: 20.255912, lng: 105.972104,
    color: '#8b5cf6', type: 'latenight', priority: false,
    location: 'Gần ga tàu cũ, Phường Thanh Bình, TP. Ninh Bình',
    locationEn: 'Near Old Railway Station, Thanh Binh Ward, Ninh Binh City',
    price: '30.000 – 70.000đ', priceEn: '30,000 – 70,000 VND',
    bestTime: 'Đêm muộn', bestTimeEn: 'Late night',
    note: 'Chuyên cơm rang dưa bò, mì xào giòn phục vụ hành khách lỡ chuyến tàu muộn hoặc người đi làm ca đêm.',
    noteEn: 'Serves fried rice with pickles and crunchy noodles for late commuters.',
  },
  {
    name: 'Ăn đêm Hoa Đô quán - 72 Xuân Thành',
    nameEn: 'Hoa Do Late Night - 72 Xuan Thanh',
    lat: 20.258124, lng: 105.964112,
    color: '#8b5cf6', type: 'latenight', priority: true,
    location: '72 Xuân Thành, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '72 Xuan Thanh Street, Tan Thanh Ward, Ninh Binh City',
    price: '40.000 – 120.000đ', priceEn: '40,000 – 120,000 VND',
    bestTime: 'Đêm muộn', bestTimeEn: 'Late night',
    note: 'Quán ăn đêm sang xịn mịn, nổi tiếng với món lẩu chim bồ câu nấm và chân gà hấp tàu xì.',
    noteEn: 'Upscale late-night food hot-spot known for pigeon hotpot and braised chicken feet.',
  },
  {
    name: 'Khoa Nguyễn - 55 Nguyễn Văn Cừ',
    nameEn: 'Khoa Nguyen Food Store',
    lat: 20.254752, lng: 105.971241,
    color: '#8b5cf6', type: 'latenight', priority: false,
    location: '55 Nguyễn Văn Cừ, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '55 Nguyen Van Cu Street, Tan Thanh Ward, Ninh Binh City',
    price: '30.000 – 60.000đ', priceEn: '30,000 – 60,000 VND',
    bestTime: 'Tối & Đêm', bestTimeEn: 'Evening & Night',
    note: 'Tiệm ăn muộn phục vụ bún kèn, mỳ cay và các món ăn nhanh tiện lợi cho giới trẻ.',
    noteEn: 'Late night snack shop serving spicy noodles and quick comfort foods.',
  },
  {
    name: 'Bánh cuốn nóng - 15 Phạm Văn Nghị',
    nameEn: '15 Pham Van Nghi Hot Rice Rolls',
    lat: 20.252412, lng: 105.973254,
    color: '#8b5cf6', type: 'latenight', priority: true,
    location: '15 Phạm Văn Nghị, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '15 Pham Van Nghi Street, Tan Thanh Ward, Ninh Binh City',
    price: '25.000 – 45.000đ', priceEn: '25,000 – 45,000 VND',
    bestTime: 'Sáng & Đêm muộn', bestTimeEn: 'Morning & Late night',
    note: 'Bánh cuốn tráng tay nóng hổi mở bán đến tận đêm khuya, thích hợp xoa dịu chiếc bụng đói sau một ngày dài.',
    noteEn: 'Freshly steamed hot rice sheets operating till midnight, an excellent comfort snack.',
  },
  {
    name: 'Huyền Bamboo',
    nameEn: 'Huyen Bamboo Restaurant',
    lat: 20.2442,
    lng: 105.9865,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '395 Nguyễn Công Trứ, Bích Đào, Ninh Bình',
    locationEn: '395 Nguyen Cong Tru Street, Bich Dao, Ninh Binh',
    price: '150.000 – 350.000đ/người',
    priceEn: '150,000 – 350,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Tiệm ăn muộn phục vụ bún kèn, mỳ cay và các món ăn nhanh tiện lợi cho giới trẻ.',
    noteEn: 'Rustic bamboo-styled space specializing in Vietnamese countryside dishes, hill chicken, and flavorful Northwest specialties.'
  },
  {
    name: 'Bánh Gối Quỳnh Mai',
    nameEn: 'Quynh Mai Fried Pillow Cake',
    lat: 20.2585, lng: 105.9702, // Tọa độ ước tính khu vực Cù Chính Lan
    color: '#ec4899', type: 'snack', priority: false,
    location: '23 Cù Chính Lan, Tân Thành, TP. Ninh Bình',
    locationEn: '23 Cu Chinh Lan Street, Tan Thanh, Ninh Binh City',
    price: '10.000 – 30.000đ', priceEn: '10,000 – 30,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Tiệm bánh gối, bánh rán nóng hổi nổi tiếng trên phố ăn vặt. Vỏ bánh giòn rụm, nhân thịt mộc nhĩ đầy đặn chấm cùng nước mắm chua ngọt đu đủ xanh.',
    noteEn: 'Crispy fried pillow cakes and donuts served with a sweet and sour dipping sauce. A perfect afternoon snack.',
  },
  {
    name: 'Cơm Tấm Sài Gòn',
    nameEn: 'Sai Gon Broken Rice',
    lat: 20.2523, lng: 105.9785, // Tọa độ ước tính khu vực Đào Duy Từ
    color: '#ef4444', type: 'asian', priority: false,
    location: '42 Đào Duy Từ, Phường Ba Đình, TP. Ninh Bình',
    locationEn: '42 Dao Duy Tu Street, Ba Dinh Ward, Ninh Binh City',
    price: '35.000 – 60.000đ', priceEn: '35,000 – 60,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Chuẩn vị cơm tấm miền Nam với sườn nướng cốt lết đậm đà thơm củi, chả trứng béo ngậy và nước mắm kẹo ngọt cay đặc trưng.',
    noteEn: 'Authentic Southern-style broken rice featuring savory grilled pork chops, egg meatloaf, and signature sweet fish sauce.',
  },
  {
    name: 'Đảo Matcha',
    nameEn: 'Matcha Island',
    lat: 20.2635, lng: 105.9680, // Tọa độ ước tính khu vực Phố cổ Hoa Lư
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Khu ẩm thực Phố cổ Hoa Lư, TP. Ninh Bình',
    locationEn: 'Food Court, Hoa Lu Old Quarter, Ninh Binh City',
    price: '25.000 – 50.000đ', priceEn: '25,000 – 50,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Điểm đến yêu thích của tín đồ trà xanh nằm ngay trong lòng Phố Cổ. Chuyên các dòng kem matcha đậm vị, thức uống giải nhiệt và bánh ngọt check-in cực chill về đêm.',
    noteEn: 'A heaven for matcha lovers located inside Hoa Lu Old Quarter. Specializing in rich matcha ice cream and refreshing drinks with a vibrant night view.',
  }
];
