// ============================================================
//  NINH BÌNH AI — Địa điểm tham quan
//  File: khudiem.js — Cập nhật 2026
// ============================================================

const ATTRACTIONS = [
  {
    name: 'Tràng An', nameEn: 'Trang An',
    lat: 20.2521, lng: 105.8728,
    color: '#ef4444', type: 'attraction', priority: true,
    ticket: '300.000đ/người lớn, 150.000đ/trẻ 1m–1m3, dưới 1m miễn phí',
    ticketEn: '300,000 VND/adult, 150,000/child 1m–1.3m, under 1m free',
    hours: '6h – 17h (bán vé đến 16h45)',
    note: 'Di sản UNESCO kép — đi thuyền qua hang động, 3 tuyến ~2.5–3h. Đặt vé online trước, đến trước 8h tránh đông.',
    noteEn: 'UNESCO dual heritage — boat through caves, 3 routes ~2.5–3hrs. Book online, arrive before 8am to avoid crowds.',
  },
  {
    name: 'Hang Múa', nameEn: 'Hang Mua',
    lat: 20.2268, lng: 105.9143,
    color: '#ef4444', type: 'attraction', priority: true,
    ticket: '150.000đ/người (từ 1m trở lên), dưới 1m miễn phí',
    ticketEn: '150,000 VND/person (over 1m tall), under 1m free',
    hours: '6h – 19h',
    note: 'Leo 486 bậc đá lên đỉnh Ngọa Long, ngắm toàn cảnh Tam Cốc. Đi lúc 6h30 sáng tránh nắng và có ảnh đẹp.',
    noteEn: '486 stone steps to Ngoa Long peak, panoramic Tam Coc view. Go at 6:30am to avoid heat and get great photos.',
  },
  {
    name: 'Tam Cốc', nameEn: 'Tam Coc',
    lat: 20.2282, lng: 105.9104,
    color: '#ef4444', type: 'attraction', priority: false,
    ticket: '250.000đ/người lớn, 125.000đ/trẻ em',
    ticketEn: '250,000 VND/adult, 125,000/child',
    hours: '7h – 17h',
    note: 'Đi thuyền qua 3 hang động, ngắm đồng lúa. Đẹp nhất tháng 5–6 lúa chín vàng.',
    noteEn: 'Boat through 3 caves past rice paddies. Most beautiful May–Jun golden rice season.',
  },
  {
    name: 'Cố đô Hoa Lư', nameEn: 'Hoa Lu Ancient Capital',
    lat: 20.2803, lng: 105.9057,
    color: '#ef4444', type: 'attraction', priority: true,
    ticket: '20.000đ/người lớn, 10.000đ/trẻ 6–15 tuổi, miễn phí trẻ dưới 6 và người trên 60 tuổi',
    ticketEn: '20,000 VND/adult, 10,000/child 6–15, free under 6 & over 60',
    hours: '7h – 17h',
    note: 'Kinh đô cổ thế kỷ X, đền thờ vua Đinh và vua Lê. Tham quan ~1h. Tối: Phố cổ Hoa Lư có đèn lồng, nhiều quán ăn ngon.',
    noteEn: '10th-century ancient capital, temples of King Dinh and King Le. ~1hr visit. Evening: Hoa Lu Old Quarter has lanterns and great food.',
  },
  {
    name: 'Chùa Bái Đính', nameEn: 'Bai Dinh Pagoda',
    lat: 20.3527, lng: 105.8708,
    color: '#ef4444', type: 'attraction', priority: false,
    ticket: 'Vào cổng miễn phí, xe điện 150.000đ/người (1 chiều, khứ hồi 300.000đ)',
    ticketEn: 'Free entry, electric cart 150,000 VND/person (one way, 300,000 VND round trip)',
    hours: '6h – 18h',
    note: 'Quần thể chùa lớn nhất Đông Nam Á. Rất rộng (539ha), nên đi xe điện. Mặc trang phục lịch sự.',
    noteEn: 'Largest pagoda complex in Southeast Asia (539ha). Take the electric cart. Dress modestly.',
  },
  {
    name: 'Đầm Vân Long', nameEn: 'Van Long Wetland Reserve',
    lat: 20.3703, lng: 105.8675,
    color: '#ef4444', type: 'attraction', priority: false,
    ticket: '150.000đ/người (thuyền)',
    ticketEn: '150,000 VND/person (boat)',
    hours: '7h30 – 17h30',
    note: 'Khu bảo tồn thiên nhiên ngập nước lớn nhất Bắc Bộ, nơi ngắm voọc quần đùi trắng. Yên bình, ít xô bồ.',
    noteEn: 'Largest wetland reserve in Northern Vietnam, home to Delacour\'s langur. Very peaceful and less touristy.',
  },
  {
    name: 'Vườn quốc gia Cúc Phương', nameEn: 'Cuc Phuong National Park',
    lat: 20.3508, lng: 105.6074,
    color: '#ef4444', type: 'attraction', priority: true,
    ticket: '60.000đ/người lớn, 10.000đ/trẻ em',
    ticketEn: '60,000 VND/adult, 10,000/child',
    hours: '7h – 17h (cổng chính)',
    note: 'Vườn quốc gia đầu tiên của Việt Nam. Nên đi tháng 4–5 mùa bướm. Cây chò ngàn năm và trung tâm cứu hộ linh trưởng.',
    noteEn: 'Vietnam\'s first national park. Best Apr–May for butterfly season. Ancient trees and primate rescue centers.',
  },
  {
    name: 'Khu du lịch sinh thái Thung Nham', nameEn: 'Thung Nham Bird Park',
    lat: 20.2078, lng: 105.9220,
    color: '#ef4444', type: 'attraction', priority: true,
    ticket: '250.000đ/người lớn, 150.000đ/trẻ em',
    ticketEn: '250,000 VND/adult, 150,000/child',
    hours: '7h – 18h',
    note: 'Nổi tiếng vườn chim tự nhiên, Động Vái Giời và Hang Bụt. Nên ghé vườn chim sau 16h để ngắm chim về tổ.',
    noteEn: 'Famous for natural bird garden, Vai Gioi Cave, and But Cave. Best to visit bird garden after 4pm.',
  },
  {
    name: 'Chùa Bích Động', nameEn: 'Bich Dong Pagoda',
    lat: 20.2177, lng: 105.9147,
    color: '#ef4444', type: 'attraction', priority: false,
    ticket: 'Miễn phí (phí gửi xe ~10.000–20.000đ)',
    ticketEn: 'Free entry (parking fee ~10,000–20,000 VND)',
    hours: 'Cả ngày (6h – 18h)',
    note: '"Nam thiên đệ nhị động". Chùa cổ 3 tầng tựa vào vách núi. Kết hợp tham quan cùng Tam Cốc rất thuận tiện.',
    noteEn: '"Second best cave in the South". Ancient 3-level pagoda built into a cliff. Great to combine with Tam Coc.',
  },
  {
    name: 'Động Thiên Hà', nameEn: 'Thien Ha Cave',
    lat: 20.2372, lng: 105.8925,
    color: '#ef4444', type: 'attraction', priority: false,
    ticket: '120.000đ/người lớn, 60.000đ/trẻ em',
    ticketEn: '120,000 VND/adult, 60,000/child',
    hours: '7h30 – 17h30',
    note: 'Hệ thống hang động thạch nhũ còn nguyên sơ, cả động khô và ướt. "Dải ngân hà trong lòng núi".',
    noteEn: 'Pristine cave system with both dry and wet sections. Nicknamed the "Galaxy inside the mountain".',
  },
  {
    name: 'Thung Ui', nameEn: 'Thung Ui',
    lat: 20.3380, lng: 105.8810,
    color: '#ef4444', type: 'attraction', priority: true,
    ticket: 'Xe điện 150.000đ/người (khứ hồi)',
    ticketEn: 'Electric cart 150,000 VND/person (round trip)',
    hours: '7h – 17h',
    note: 'Hành cung Hoa Lư xưa, hoang sơ ít người biết, văn hóa Mường độc đáo. Gần Bái Đính ~3km.',
    noteEn: 'Former royal retreat, off-the-beaten-path, unique Muong culture. Near Bai Dinh ~3km.',
  },
  {
    name: 'Động Am Tiên (Tuyệt Tịnh Cốc)', nameEn: 'Am Tien Cave',
    lat: 20.2831, lng: 105.9083,
    color: '#ef4444', type: 'attraction', priority: false,
    ticket: '100.000đ/người lớn, 50.000đ/trẻ em',
    ticketEn: '100,000 VND/adult, 50,000/child',
    hours: '7h – 17h',
    note: 'Trong quần thể Hoa Lư, hồ nước xanh ngắt quanh năm. Thích hợp check-in và tận hưởng không khí tĩnh lặng.',
    noteEn: 'Located within Hoa Lu complex, featuring a year-round turquoise lake. Perfect for photography and quiet atmosphere.',
  },
];
