// ============================================================
//  NINH BÌNH AI — Nhà hàng & Mua sắm
//  File: nhahang.js — Cập nhật mới nhất
// ============================================================

const RESTAURANTS = [
  { name: 'Heo Say Xỉn (GC22-23)', nameEn: 'Heo Say Xin (GC22-23)', lat: 20.2491, lng: 105.9768, color: '#f59e0b', type: 'food', priority: true, location: 'Gian hàng GC22-23, Phố cổ Hoa Lư', locationEn: 'Stall GC22-23, Hoa Lu Old Quarter', price: 'Tầm trung', priceEn: 'Mid-range', bestTime: 'Buổi tối', bestTimeEn: 'Evening', note: 'Heo nuôi bằng rượu & thảo dược, da giòn thịt mềm. "Vietnam\'s Kobe Pork". Nên đến sớm vì hay hết.', noteEn: 'Pork raised on rice wine & herbs, crispy skin. "Vietnam\'s Kobe Pork". Arrive early — sells out fast.' },
  { name: 'Lẩu Gà Lá É (GC57-58)', nameEn: 'Lau Ga La E (GC57-58)', lat: 20.2488, lng: 105.9771, color: '#f59e0b', type: 'food', priority: true, location: 'Gian hàng GC57-58, Phố cổ Hoa Lư', locationEn: 'Stall GC57-58, Hoa Lu Old Quarter', price: '300.000 – 500.000đ/nồi', priceEn: '300,000 – 500,000 VND/pot', bestTime: 'Buổi tối', bestTimeEn: 'Evening', note: 'Lẩu gà thảo mộc chuẩn vị Đà Lạt, nước dùng ngọt thanh từ lá é. Chill, view phố cổ đẹp về đêm.', noteEn: 'Da Lat-style herb chicken hotpot. Chill vibe with great Old Quarter night view.' },
  { name: 'Đại Long Building — Cơm Cháy', nameEn: 'Dai Long Building — Burnt Rice', lat: 20.2540, lng: 105.9720, color: '#10b981', type: 'shop', priority: true, location: '325A Đường Lê Thái Tổ, Ninh Bình', locationEn: '325A Le Thai To Street, Ninh Binh', price: 'Nhiều mức giá', priceEn: 'Various price ranges', bestTime: 'Cả ngày', bestTimeEn: 'All day', note: 'Địa chỉ uy tín mua cơm cháy làm quà. Nhiều loại đóng gói sẵn, có thể ship về.', noteEn: 'Trusted address for burnt rice souvenirs. Pre-packaged options, can be shipped.' },
  { name: 'Dê Chính Thư (Tràng An)', nameEn: 'Chinh Thu Goat Meat', lat: 20.2515, lng: 105.9182, color: '#f59e0b', type: 'food', priority: true, location: 'Khê Thượng, Ninh Xuân, Hoa Lư', locationEn: 'Khe Thuong, Ninh Xuan, Hoa Lu', price: '200.000 – 400.000đ/người', priceEn: '200,000 – 400,000 VND/person', bestTime: 'Buổi trưa', bestTimeEn: 'Lunch time', note: 'Quán dê nổi tiếng nhất vùng Tràng An. Dê tái chanh và cơm cháy sốt dê là must-try.', noteEn: 'Most famous goat restaurant near Trang An. Must-try: lime-marinated goat and burnt rice with goat sauce.' },
  { name: 'Nhà hàng Thung Nham', nameEn: 'Thung Nham Restaurant', lat: 20.2685, lng: 105.9500, color: '#f59e0b', type: 'food', priority: true, location: 'Xã Ninh Hải, Hoa Lư (Khu du lịch sinh thái Thung Nham)', locationEn: 'Ninh Hai Commune, Hoa Lu (Thung Nham Ecotourism Area)', price: '200.000 – 450.000đ/người', priceEn: '200,000 – 450,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Nhà hàng dê núi kết hợp view thiên nhiên tuyệt đẹp. Không gian thoáng đãng, phù hợp khách thích không gian xanh.', noteEn: 'Mountain goat restaurant with stunning natural views. Spacious green setting. Great for nature lovers.' },
  { name: 'Nhà hàng Hoàng Giang', nameEn: 'Hoang Giang Restaurant', lat: 20.2750, lng: 105.9100, color: '#f59e0b', type: 'food', priority: true, location: 'Núi Hang Cá, Trường Yên, Hoa Lư', locationEn: 'Hang Ca Mountain, Truong Yen, Hoa Lu', price: '180.000 – 400.000đ/người', priceEn: '180,000 – 400,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Nhà hàng dê núi trong vùng lõi Tràng An, khuôn viên 5ha, view núi non. Phù hợp cho đoàn khách.', noteEn: 'Goat restaurant inside Trang An. Huge 5ha garden with mountain views. Ideal for groups.' },
  { name: 'Nhà hàng Thanh Cao', nameEn: 'Thanh Cao Restaurant', lat: 20.2600, lng: 105.9700, color: '#f59e0b', type: 'food', priority: true, location: 'Khu vực Đông Thành / Hoa Lư, Ninh Bình', locationEn: 'Dong Thanh / Hoa Lu area, Ninh Binh', price: '200.000 – 500.000đ/người', priceEn: '200,000 – 500,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Nhà hàng dê núi nổi tiếng bậc nhất Ninh Bình. Chuyên dê tươi, chế biến đa dạng, không gian rộng rãi.', noteEn: 'One of the most famous mountain goat restaurants in Ninh Binh. Fresh goat with varied preparations.' },
  { name: 'Hoang Cuisine Vietnamese Restaurant', nameEn: 'Hoang Cuisine Vietnamese Restaurant', lat: 20.2200, lng: 105.9200, color: '#f59e0b', type: 'food', priority: true, location: 'Tam Cốc, Ninh Hải, Hoa Lư', locationEn: 'Tam Coc, Ninh Hai, Hoa Lu', price: '150.000 – 350.000đ/người', priceEn: '150,000 – 350,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Nhà hàng Việt được đánh giá cao, có cả món chay. Phục vụ thân thiện, phù hợp khách Việt và quốc tế.', noteEn: 'Highly rated Vietnamese restaurant with vegetarian options. Friendly service, for locals and tourists.' },
  { name: 'Cơm Niêu Việt Xưa CS1 (Tràng An)', nameEn: 'Com Nieu Viet Xua CS1 (Trang An)', lat: 20.2630, lng: 105.9755, color: '#f59e0b', type: 'food', priority: true, location: '80-82 Đường Tràng An, Tân Thành, Hoa Lư', locationEn: '80-82 Trang An Street, Tan Thanh, Hoa Lu', price: '100.000 – 250.000đ/người', priceEn: '100,000 – 250,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Cơ sở chính đối diện Phố cổ Hoa Lư. Cơm niêu truyền thống đậm đà, menu thuần Việt, set cơm từ 100k/người.', noteEn: 'Main branch opposite Hoa Lu Old Quarter. Traditional claypot rice, affordable set meals from 100k/person.' },
  { name: 'Cơm Niêu Việt Xưa CS2 (Tam Cốc)', nameEn: 'Com Nieu Viet Xua CS2 (Tam Coc)', lat: 20.2355, lng: 105.9305, color: '#f59e0b', type: 'food', priority: true, location: 'Thôn Đam Khê Ngoài, Ninh Hải, Hoa Lư', locationEn: 'Dam Khe Ngoai Village, Ninh Hai, Hoa Lu', price: '100.000 – 250.000đ/người', priceEn: '100,000 – 250,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Cơ sở tại Tam Cốc. Không gian rộng phục vụ 500 khách. Rất tiện cho khách tham quan Tam Cốc - Bích Động.', noteEn: 'Tam Coc branch. Very spacious (500 guests). Convenient for Tam Coc visitors.' },
  { name: 'Cơm Niêu Việt Xưa CS3 (Bái Đính)', nameEn: 'Com Nieu Viet Xua CS3 (Bai Dinh)', lat: 20.2450, lng: 105.8700, color: '#f59e0b', type: 'food', priority: true, location: 'Tổ 5, Tây Hoa Lư (gần cổng chùa Bái Đính)', locationEn: 'Group 5, Tay Hoa Lu (near Bai Dinh gate)', price: '100.000 – 250.000đ/người', priceEn: '100,000 – 250,000 VND/person', bestTime: 'Trưa', bestTimeEn: 'Lunch', note: 'Cơ sở gần Bái Đính. Phù hợp khách hành hương và tham quan chùa.', noteEn: 'Branch near Bai Dinh Pagoda. Suitable for pilgrims and temple visitors.' },
  { name: 'Kombo - Cơm Niêu Singapore', nameEn: 'Kombo - Singapore Claypot Rice', lat: 20.2550, lng: 105.9750, color: '#f59e0b', type: 'food', priority: true, location: '94 Đinh Tiên Hoàng, Đông Thành, Ninh Bình', locationEn: '94 Dinh Tien Hoang Street, Dong Thanh, Ninh Binh', price: '80.000 – 200.000đ/người', priceEn: '80,000 – 200,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Cơm niêu Singapore phong cách hiện đại, máy lạnh. Cơm cháy giòn, topping đa dạng (bò sốt tiêu đen, gà sốt nấm...).', noteEn: 'Modern Singapore-style claypot rice with AC. Crispy burnt rice with rich toppings (black pepper beef, mushroom chicken...).' },
  { name: 'Cơm Thố Anh Nguyễn', nameEn: 'Anh Nguyen Claypot Rice', lat: 20.2545, lng: 105.9750, color: '#f59e0b', type: 'food', priority: true, location: '207 Lương Văn Thăng, Hoa Lư, Ninh Bình', locationEn: '207 Luong Van Thang Street, Hoa Lu, Ninh Binh', price: '45.000 – 80.000đ/suất', priceEn: '45,000 – 80,000 VND/portion', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Chuỗi cơm thố nổi tiếng toàn quốc. Menu đa dạng, cơm cháy giòn thơm, giá bình dân.', noteEn: 'Famous nationwide claypot rice chain. Diverse menu, crispy burnt rice, affordable prices.' },
  { name: 'Cơm Đốt Thố Lão Đại', nameEn: 'Lao Dai Burnt Claypot Rice', lat: 20.2498, lng: 105.9765, color: '#f59e0b', type: 'food', priority: true, location: '85 Trần Hưng Đạo, đối diện Phố cổ Hoa Lư', locationEn: '85 Tran Hung Dao Street, opposite Hoa Lu Old Quarter', price: '65.000 – 90.000đ/suất', priceEn: '65,000 – 90,000 VND/portion', bestTime: 'Buổi tối', bestTimeEn: 'Evening', note: 'Vị trí tiện ngay khu Phố cổ. Cơm đốt thố cháy giòn, menu đa dạng, đỗ xe thoải mái.', noteEn: 'Super convenient opposite Old Quarter. Crispy burnt claypot rice. Easy parking.' },
  { name: 'Bún Chả Quạt Tình Mai', nameEn: 'Tinh Mai Grilled Pork Noodles', lat: 20.2522, lng: 105.9744, color: '#f59e0b', type: 'food', priority: true, location: '07 Phạm Hồng Thái, Phố 3, Ninh Bình', locationEn: '07 Pham Hong Thai, Ward 3, Ninh Binh', price: '40.000đ/suất', priceEn: '40,000 VND/portion', bestTime: 'Sáng sớm (6h–10h)', bestTimeEn: 'Early morning only (6–10am)', note: 'Chả quạt miếng to, nướng cháy cạnh thơm lừng, ăn kèm bún lá. Món ăn sáng/trưa đặc trưng.', noteEn: 'Big grilled pork patties, smoky and flavorful. A signature local breakfast/lunch.' },
  { name: 'Nhà hàng Đức Dê', nameEn: 'Duc De Restaurant', lat: 20.2578, lng: 105.9735, color: '#f59e0b', type: 'food', priority: true, location: '446 Nguyễn Huệ, Ninh Bình', locationEn: '446 Nguyen Hue, Ninh Binh', price: '250.000 – 500.000đ/người', priceEn: '250,000 – 500,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Thương hiệu dê núi lâu đời bậc nhất Ninh Bình. Kỹ thuật chế biến khử mùi tuyệt đối, không gian truyền thống.', noteEn: 'Oldest goat brand in Ninh Binh. Famous technique to remove gamey smell. Traditional decor.' },
  { name: 'Gỏi Nhệch Vũ Bảo', nameEn: 'Vu Bao Rice Field Eel Salad', lat: 20.2612, lng: 105.9688, color: '#f59e0b', type: 'food', priority: true, location: '37 Nguyễn Huệ, Ninh Bình', locationEn: '37 Nguyen Hue, Ninh Binh', price: '200.000 – 350.000đ/người', priceEn: '200,000 – 350,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Đặc sản gỏi nhệch Kim Sơn. Ăn kèm lá rừng và nước chẻo nóng hổi. Trải nghiệm ẩm thực cực kỳ độc đáo.', noteEn: 'Kim Son specialty eel salad with wild leaves and hot ginger sauce. A unique culinary experience.' },
  { name: 'Nhà hàng Thăng Long', nameEn: 'Thang Long Restaurant', lat: 20.2765, lng: 105.9185, color: '#f59e0b', type: 'food', priority: true, location: 'Tràng An, Trường Yên, Hoa Lư', locationEn: 'Trang An, Truong Yen, Hoa Lu', price: '150.000 – 300.000đ/người', priceEn: '150,000 – 300,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Gần chùa Bái Đính và Tràng An. Không gian rộng, dê núi, cơm cháy. Phù hợp cho khách đoàn.', noteEn: 'Near Bai Dinh and Trang An. Spacious, goat meat and burnt rice. Ideal for groups.' },
  { name: 'Nhà hàng Ba Cửa', nameEn: 'Ba Cua Restaurant', lat: 20.2707, lng: 105.9137, color: '#f59e0b', type: 'food', priority: true, location: 'Thôn Tràng An, Trường Yên, Hoa Lư', locationEn: 'Trang An Hamlet, Truong Yen, Hoa Lu', price: '200.000 – 300.000đ/người', priceEn: '200,000 – 300,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Trong vùng lõi di sản. Sân vườn rộng. Dê núi ủ trấu và cá rô Tổng Trường rất ngon.', noteEn: 'In the heart of the heritage site. Spacious garden. Straw-roasted goat and Tong Truong fish.' },
  { name: 'Dũng Phố Núi', nameEn: 'Dung Pho Nui Restaurant', lat: 20.2525, lng: 105.9260, color: '#f59e0b', type: 'food', priority: true, location: 'Ninh Xuân, Hoa Lư (Gần bến thuyền Tràng An)', locationEn: 'Ninh Xuan, Hoa Lu (Near Trang An Wharf)', price: '150.000 – 350.000đ/người', priceEn: '150,000 – 350,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Rất đông khách, dê núi truyền thống. Phục vụ nhanh, menu đa dạng từ dê tái chanh đến dê xào lăn.', noteEn: 'Very popular for traditional goat dishes. Fast service from lime-marinated to stir-fried goat.' },
  { name: 'Nhà hàng Khoa Anh', nameEn: 'Khoa Anh Restaurant', lat: 20.2178, lng: 105.9230, color: '#f59e0b', type: 'food', priority: true, location: 'Thôn Đam Khê, Ninh Hải, Hoa Lư', locationEn: 'Dam Khe Village, Ninh Hai, Hoa Lu', price: '150.000 – 350.000đ/người', priceEn: '150,000 – 350,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'View cánh đồng lúa và sông Ngô Đồng. Không gian mở thoáng. Dê núi và cá sông.', noteEn: 'Overlooking rice fields and Ngo Dong river. Open-air. Mountain goat and river fish.' },
  { name: 'The Banana Tree Hostel (Pool Bar & Resto)', nameEn: 'The Banana Tree Hostel', lat: 20.2180, lng: 105.9248, color: '#f59e0b', type: 'food', priority: true, location: 'Cạnh bến thuyền Tam Cốc', locationEn: 'Next to Tam Coc Wharf', price: '100.000 – 300.000đ', priceEn: '100,000 – 300,000 VND', bestTime: 'Buổi tối', bestTimeEn: 'Evening', note: 'Không gian chill có bể bơi, nhạc hay. Giới trẻ ăn tối và uống cocktail ngắm bến thuyền.', noteEn: 'Chill vibe with pool and good music. Perfect for dinner and cocktails at the wharf.' },
  { name: 'Nhà hàng Cao Sơn', nameEn: 'Cao Son Restaurant', lat: 20.2458, lng: 105.8752, color: '#f59e0b', type: 'food', priority: true, location: 'Xã Gia Sinh, Gia Viễn (Gần cổng chùa Bái Đính)', locationEn: 'Gia Sinh, Gia Vien (Near Bai Dinh Pagoda Gate)', price: '150.000 – 350.000đ/người', priceEn: '150,000 – 350,000 VND/person', bestTime: 'Buổi trưa', bestTimeEn: 'Lunch time', note: 'Lớn và uy tín nhất khu Bái Đính. Chuyên cơm cháy, dê núi. Không gian sang trọng.', noteEn: 'Most reputable near Bai Dinh. Burnt rice and goat dishes. Upscale setting.' },
  { name: 'Buffet Chay chùa Bái Đính', nameEn: 'Bai Dinh Pagoda Vegan Buffet', lat: 20.2440, lng: 105.8715, color: '#f59e0b', type: 'food', priority: true, location: 'Trong khuôn viên chùa Bái Đính', locationEn: 'Inside Bai Dinh Pagoda Complex', price: '100.000 – 150.000đ/người', priceEn: '100,000 – 150,000 VND/person', bestTime: 'Buổi trưa', bestTimeEn: 'Lunch time', note: 'Ẩm thực chay ngay tại chùa. Đa dạng từ nông sản địa phương. Phù hợp khách hành hương.', noteEn: 'Peaceful vegan dining inside the pagoda. Local produce dishes. Ideal for pilgrims.' },
  { name: 'Tiệm Trà Chanh Phố Cổ (GC01)', nameEn: 'Ancient Town Tea Stall (GC01)', lat: 20.2495, lng: 105.9760, color: '#f59e0b', type: 'food', priority: true, location: 'Gian hàng GC01, Phố cổ Hoa Lư', locationEn: 'Stall GC01, Hoa Lu Old Quarter', price: '20.000 – 50.000đ', priceEn: '20,000 – 50,000 VND', bestTime: 'Buổi tối', bestTimeEn: 'Evening', note: 'Vị trí đắc địa, view trực diện hồ Kỳ Lân. Uống trà, ngắm dòng người và xem biểu diễn nghệ thuật.', noteEn: 'Prime spot with Ky Lan Lake view. Sipping tea while watching street performances.' },
  { name: 'Chookie\'s Beer Garden', nameEn: 'Chookie\'s Beer Garden', lat: 20.2168, lng: 105.9411, color: '#06b6d4', type: 'food', priority: true, location: 'Đường Tam Cốc, Ninh Hải, Hoa Lư', locationEn: 'Tam Coc Rd, Ninh Hai, Hoa Lu', price: '100.000 – 300.000đ', priceEn: '100,000 – 300,000 VND', bestTime: 'Buổi tối', bestTimeEn: 'Evening', note: 'Điểm tụ tập số 1 của giới trẻ và khách bụi. Pizza, Burger đến bia thủ công. Sân vườn rộng thoải mái.', noteEn: 'Top spot for backpackers and youth. Pizza, Burgers to craft beer. Spacious garden.' },
  { name: 'Nhà hàng Lương Thương', nameEn: 'Luong Thuong Restaurant', lat: 20.2648, lng: 105.9750, color: '#f59e0b', type: 'food', priority: true, location: 'Chân cầu Non Nước, Phố 4, Đông Thành, Ninh Bình', locationEn: 'Non Nuoc Bridge, Ward 4, Dong Thanh, Ninh Binh', price: '200.000 – 450.000đ/người', priceEn: '200,000 – 450,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Nhà hàng dê núi lâu năm. Không gian nhiều tầng, dê núi tươi và gà đồi. Phù hợp đoàn khách.', noteEn: 'Long-standing goat restaurant. Multi-floor venue, fresh goat and hill chicken. Good for groups.' },
  { name: 'Nhà hàng Thành Long', nameEn: 'Thanh Long Restaurant', lat: 20.2635, lng: 105.9740, color: '#f59e0b', type: 'food', priority: true, location: 'Số 4 Ngô Quyền, Đông Thành, Ninh Bình', locationEn: 'No. 4 Ngo Quyen Street, Dong Thanh, Ninh Binh', price: '200.000 – 500.000đ/người', priceEn: '200,000 – 500,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Nổi tiếng với dê quay nguyên con, dê ủ trấu, dê áp chảo. Không gian rộng, phục vụ tốt.', noteEn: 'Famous for whole roasted goat, straw-roasted goat, and stir-fried goat. Spacious, good service.' },
  { name: 'Nhà hàng Dê Chính Thư 2', nameEn: 'Chinh Thu Goat Restaurant 2', lat: 20.2350, lng: 105.9300, color: '#f59e0b', type: 'food', priority: true, location: 'Đường du lịch Tam Cốc - Bích Động, Ninh Hải, Hoa Lư', locationEn: 'Tam Coc - Bich Dong tourist road, Ninh Hai, Hoa Lu', price: '180.000 – 400.000đ/người', priceEn: '180,000 – 400,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Cơ sở 2 của quán dê Chính Thư. Gần Tam Cốc - Bích Động. Thịt dê chắc, chế biến đa dạng.', noteEn: 'Branch 2 of Chinh Thu. Near Tam Coc - Bich Dong. Fresh goat with various preparations.' },
  { name: 'Nhà hàng Tam Gia Trang', nameEn: 'Tam Gia Trang Restaurant', lat: 20.2625, lng: 105.9646, color: '#f59e0b', type: 'food', priority: true, location: '35 Tràng An 2, Tân Thành, Hoa Lư', locationEn: '35 Trang An 2, Tan Thanh, Hoa Lu', price: '150.000 – 300.000đ/người', priceEn: '150,000 – 300,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Thiết kế phong cách kiếm hiệp độc đáo. Đồ ăn ngon, trang trí đẹp, nhóm bạn trẻ thích trải nghiệm lạ.', noteEn: 'Unique Wuxia-themed decor. Good food, great for young groups seeking a themed experience.' },
  { name: 'The Aria Cafe', nameEn: 'The Aria Cafe', lat: 20.2715, lng: 105.9772, color: '#06b6d4', type: 'food', priority: true, location: '144A4 Lê Hồng Phong, Hoa Lư', locationEn: '144A4 Le Hong Phong, Hoa Lu', price: '40.000 – 80.000đ', priceEn: '40,000 – 80,000 VND', bestTime: 'Sáng & Chiều', bestTimeEn: 'Morning & Afternoon', note: 'Phong cách Châu Âu sang chảnh với bể bơi ngoài trời. Địa điểm "sống ảo" hàng đầu Ninh Bình.', noteEn: 'Elegant European style with outdoor pool. Top check-in spot for local youth.' },
  { name: 'Mona Lisa Tam Coc', nameEn: 'Mona Lisa Tam Coc', lat: 20.2182, lng: 105.9238, color: '#f59e0b', type: 'food', priority: true, location: 'Trung tâm khu du lịch Tam Cốc', locationEn: 'Tam Coc Tourist Center', price: '150.000 – 400.000đ', priceEn: '150,000 – 400,000 VND', bestTime: 'Buổi tối', bestTimeEn: 'Evening', note: 'Giao thoa Ý - Việt. Pizza lò củi ngon và ban công nhìn xuống phố Tam Cốc nhộn nhịp.', noteEn: 'Italian-Vietnamese fusion. Wood-fired pizza and balcony overlooking the Tam Coc street.' },
  { name: 'Sân Cafe & Bistro', nameEn: 'San Cafe & Bistro', lat: 20.2515, lng: 105.9765, color: '#06b6d4', type: 'food', priority: true, location: 'Khu biệt thự ven hồ Kỳ Lân, Hoa Lư', locationEn: 'Ky Lan Lakeside Villas, Hoa Lu', price: '45.000 – 120.000đ', priceEn: '45,000 – 120,000 VND', bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening', note: 'Không gian mở hiện đại, tinh tế. Hẹn hò hoặc gặp đối tác trong không gian yên tĩnh.', noteEn: 'Modern, sophisticated open space. Ideal for elegant dates or quiet meetings.' },
  { name: 'Trung Tuyết Restaurant', nameEn: 'Trung Tuyet Restaurant', lat: 20.2550, lng: 105.9750, color: '#f59e0b', type: 'food', priority: true, location: 'Trung tâm Ninh Bình (gần Phố cổ Hoa Lư)', locationEn: 'Ninh Binh city center (near Hoa Lu Old Quarter)', price: '100.000 – 300.000đ/người', priceEn: '100,000 – 300,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Đánh giá cao nhất Ninh Bình. Món Việt đa dạng, không gian sạch, phù hợp gia đình và nhóm bạn.', noteEn: 'Highest-rated in Ninh Binh. Diverse Vietnamese dishes, clean space, great for families.' },
  { name: 'Thảo Béo Restaurant Bar', nameEn: 'Thao Beo Restaurant Bar', lat: 20.2185, lng: 105.9235, color: '#f59e0b', type: 'food', priority: true, location: 'Tam Cốc, Ninh Hải, Hoa Lư', locationEn: 'Tam Coc, Ninh Hai, Hoa Lu', price: '120.000 – 280.000đ/người', priceEn: '120,000 – 280,000 VND/person', bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Dinner', note: 'Quán gia đình ấm cúng, có món chay, phục vụ thân thiện. Khách quốc tế khen nhiều.', noteEn: 'Cozy family restaurant, vegetarian options, friendly service. Praised by international tourists.' },
  { 
    name: 'Bún Chả Thế Ngọc', 
    nameEn: 'The Ngoc Grilled Pork Noodles', 
    lat: 20.2520, 
    lng: 105.9740, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '16 Phạm Hồng Thái, Vân Giang, Ninh Bình', 
    locationEn: '16 Pham Hong Thai Street, Van Giang, Ninh Binh', 
    price: '25.000 – 50.000đ/suất', 
    priceEn: '25,000 – 50,000 VND/portion', 
    bestTime: 'Buổi sáng', 
    bestTimeEn: 'Morning', 
    note: 'Quán bún chả quạt lâu đời, thịt nướng phên miếng to, thơm ngon đậm vị, giá bình dân.', 
    noteEn: 'Long-standing grilled pork noodle shop, big and flavorful pork patties, affordable price.' 
  },
  { 
    name: 'Bún Mọc Tố Như', 
    nameEn: 'To Nhu Rice Noodles with Meatballs', 
    lat: 20.2562, 
    lng: 105.9745, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Số 37 ngõ 74 Đường Đinh Tiên Hoàng, Đông Thành, Ninh Bình', 
    locationEn: 'No 37, Alley 74 Dinh Tien Hoang Street, Dong Thanh, Ninh Binh', 
    price: '30.000 – 50.000đ/bát', 
    priceEn: '30,000 – 50,000 VND/bowl', 
    bestTime: 'Buổi sáng (5h–12h)', 
    bestTimeEn: 'Morning (5am–12pm)', 
    note: 'Đặc sản bún mọc tách riêng bún và nước dùng kèm mọc, nước dùng trong veo ngọt thanh.', 
    noteEn: 'Specialty noodle soup served with separate noodles and meatballs in clear, sweet broth.' 
  },
    {
    name: 'Nhà Hàng Tùng Anh - 58 Đ. Lương Văn Thăng',
    nameEn: 'Tung Anh Restaurant',
    lat: 20.257122, lng: 105.979104,
    color: '#8b5cf6', type: 'latenight', priority: false,
    location: '58 Đường Lương Văn Thăng, Phường Đông Thành, TP. Ninh Bình',
    locationEn: '58 Luong Van Thang Street, Dong Thanh Ward, Ninh Binh City',
    price: '50.000 – 200.000đ', priceEn: '50,000 – 200,000 VND',
    bestTime: 'Trưa & Đêm', bestTimeEn: 'Lunch & Late night',
    note: 'Nhà hàng mở muộn phục vụ các món ăn từ hải sản, chim câu và đặc sản dê núi Ninh Bình.',
    noteEn: 'Late-opening dining room featuring local mountain goat and fresh seafood variations.',
  },
  {
    name: 'La Lumière Tam Cốc',
    nameEn: 'La Lumiere Tam Coc',
    lat: 20.2312,
    lng: 105.9285,
    color: '#06b6d4',
    type: 'food',
    priority: true,
    location: 'Thôn Đam Khê Trong, Ninh Hải, Hoa Lư, Ninh Bình',
    locationEn: 'Dam Khe Trong Village, Ninh Hai, Hoa Lu, Ninh Binh',
    price: '45.000 – 95.000đ',
    priceEn: '45,000 – 95,000 VND',
    bestTime: 'Sáng & Chiều',
    bestTimeEn: 'Morning & Afternoon',
    note: 'Tổ hợp cafe & check-in tuyệt đẹp nằm ẩn mình tại làng cổ Đam Khê Trong. Không gian thiết kế nghệ thuật, view nhìn thẳng ra cánh đồng lúa và núi đá vôi trùng điệp, cực kỳ yên bình.',
    noteEn: 'Stunning cafe & check-in complex hidden in the ancient Dam Khe Trong village. Artistically designed space with views of rice fields and limestone mountains.'
  },
    {
    name: 'Gỏi cá - 104 Lê Thánh Tông',
    nameEn: '104 Le Thanh Tong Raw Fish Salad',
    lat: 20.267542, lng: 105.978241,
    color: '#8b5cf6', type: 'latenight', priority: true,
    location: '104 Lê Thánh Tông, Phường Đông Thành, TP. Ninh Bình',
    locationEn: '104 Le Thánh Tong Street, Dong Thanh Ward, Ninh Binh City',
    price: '80.000 – 150.000đ', priceEn: '80,000 – 150,000 VND',
    bestTime: 'Chiều & Đêm', bestTimeEn: 'Afternoon & Late night',
    note: 'Đặc sản gỏi cá nhệch Kim Sơn chuẩn vị, cá tươi thính thơm lừng cuốn lá sung và nước chẻo nóng hổi béo ngậy.',
    noteEn: 'Serving authentic Kim Son raw fish salad with aromatic roasted rice powder and rich warm dipping sauce.',
  },
  {
    name: 'Phở Kim Hải 35',
    nameEn: 'Kim Hai 35 Pho Restaurant',
    lat: 20.2546,
    lng: 105.9714,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '206 Lê Thái Tổ, Tân Thành, Ninh Bình',
    locationEn: '206 Le Thai To Street, Tan Thanh, Ninh Binh',
    price: '40.000 – 65.000đ/bát',
    priceEn: '40,000 – 65,000 VND/bowl',
    bestTime: 'Buổi sáng',
    bestTimeEn: 'Morning',
    note: 'Quán phở gia truyền nổi tiếng trên trục đường Lê Thái Tổ. Nước dùng bò, gà ninh xương trong vắt, ngọt thanh tự nhiên, thịt bò tươi mềm được thái và chế biến khéo léo.',
    noteEn: 'Famous traditional Pho restaurant on Le Thai To Street. Known for its crystal-clear, naturally sweet bone broth, and tender, fresh beef slices.'
  },
  {
    name: 'Hải Quán',
    nameEn: 'Hai Quan Restaurant',
    lat: 20.2573,
    lng: 105.9782,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '06 Nguyễn Lương Bằng, Tân Thành, Ninh Bình',
    locationEn: '06 Nguyen Luong Bang Street, Tan Thanh, Ninh Binh',
    price: '150.000 – 300.000đ/người',
    priceEn: '150,000 – 300,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Quán ăn chuyên các món nhậu dân dã, gà đồi, cá sông và đặc sản địa phương tươi ngon. Không gian bình dân, sạch sẽ, phục vụ chu đáo, rất hợp cho các buổi tụ tập gia đình, bạn bè.',
    noteEn: 'A local restaurant specializing in rustic drinking dishes, hill chicken, river fish, and fresh local specialties. Casual and clean space, great for social gatherings.'
  },
  { 
    name: 'Bánh Cuốn Bà Én', 
    nameEn: 'Ba En Steamed Rice Rolls', 
    lat: 20.2514, 
    lng: 105.9748, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '29 Phạm Hồng Thái, Vân Giang, Ninh Bình', 
    locationEn: '29 Pham Hong Thai Street, Van Giang, Ninh Binh', 
    price: '25.000 – 35.000đ/suất', 
    priceEn: '25,000 – 35,000 VND/portion', 
    bestTime: 'Buổi sáng & Tối', 
    bestTimeEn: 'Morning & Evening', 
    note: 'Bánh tráng mỏng mướt đổ nóng hổi, chả mềm ngon ăn kèm nước chấm hành phi gia truyền.', 
    noteEn: 'Thin and smooth steamed rice rolls served hot with soft pork patties and traditional shallot sauce.' 
  },
  {
    name: 'Mộc Vị Hoa Lư',
    nameEn: 'Moc Vi Hoa Lu Restaurant',
    lat: 20.2492,
    lng: 105.9766,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Khu gian hàng ẩm thực, Phố cổ Hoa Lư, Ninh Bình',
    locationEn: 'Food Stall Area, Hoa Lu Old Quarter, Ninh Binh',
    price: '50.000 – 150.000đ/người',
    priceEn: '50,000 – 150,000 VND/person',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Không gian mộc mạc đậm chất truyền thống trong lòng phố cổ. Chuyên các món ăn dân dã, đồ ăn vặt Cố đô và các thức uống thanh mát phù hợp cho khách dạo phố đêm.',
    noteEn: 'Rustic and traditional space inside the Old Quarter. Specializing in local folk dishes, Ancient Town snacks, and refreshing drinks for night walkers.'
  },
  {
    name: 'Tây Bắc Quán (Phố Cổ)',
    nameEn: 'Tay Bac Quan (Old Quarter)',
    lat: 20.2489,
    lng: 105.9769,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Khu gian hàng ẩm thực, Phố cổ Hoa Lư, Ninh Bình',
    locationEn: 'Food Stall Area, Hoa Lu Old Quarter, Ninh Binh',
    price: '100.000 – 250.000đ/người',
    priceEn: '100,000 – 250,000 VND/person',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Mang hương vị núi rừng về giữa lòng Cố đô. Nổi tiếng với các món nướng mắc khén, hạt dổi, trâu gác bếp và các món nhậu đặc trưng vùng cao Tây Bắc.',
    noteEn: 'Bringing Northwest mountain flavors to the heart of the Ancient Town. Famous for grilled dishes with Mac Khen seeds, smoked buffalo meat, and highland specialty foods.'
  },
  { 
    name: 'Bánh Cuốn Mẹt Hương Hương', 
    nameEn: 'Huong Huong Steamed Rice Rolls', 
    lat: 20.2472, 
    lng: 105.9785, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '60 Đường Võ Thị Sáu, Tân Thành, Ninh Bình', 
    locationEn: '60 Vo Thi Sau Street, Tan Thành, Ninh Binh', 
    price: '30.000 – 50.000đ/suất', 
    priceEn: '30,000 – 50,000 VND/portion', 
    bestTime: 'Buổi sáng', 
    bestTimeEn: 'Morning', 
    note: 'Bánh cuốn mẹt trình bày đẹp mắt, đầy đặn topping chả, thịt nướng, rau sống sạch sẽ.', 
    noteEn: 'Steamed rice rolls served on traditional trays with rich toppings like pork patties, grilled meat.' 
  },
{ 
    name: 'Bánh xèo mềm Cô Oanh', 
    nameEn: 'Co Oanh Soft Vietnamese Crepe (Banh Xeo)', 
    lat: 20.24693, 
    lng: 105.98894, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '32 Ngõ 385 Đường Nguyễn Công Trứ, Phường Thanh Bình, Ninh Bình', 
    locationEn: '32 Alley 385 Nguyen Cong Tru Street, Thanh Binh Ward, Ninh Binh', 
    price: '20.000 – 50.000đ/người', 
    priceEn: '20,000 – 50,000 VND/person', 
    bestTime: 'Chiều & Tối', 
    bestTimeEn: 'Afternoon & Evening', 
    note: 'Quán bánh xèo mềm vỏ dai nhẹ đặc trưng kiểu miền Trung, nhân thịt tôm đầy đặn, nước chấm chua ngọt ăn kèm rau sống siêu cuốn.', 
    noteEn: 'Famous for Central-style soft crepes with a subtly chewy crust, generous shrimp and pork filling, served with sweet-sour dipping sauce and fresh herbs.' 
  },
  { 
    name: 'Bánh Canh Cá Lóc Huế', 
    nameEn: 'Hue Snakehead Fish Thick Noodles', 
    lat: 20.2505, 
    lng: 105.9760, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '57 Trần Hưng Đạo, Tân Thành, Ninh Bình', 
    locationEn: '57 Tran Hung Dao Street, Tan Thanh, Ninh Binh', 
    price: '30.000 – 50.000đ/bát', 
    priceEn: '30,000 – 50,000 VND/bowl', 
    bestTime: 'Sáng & Chiều Tối', 
    bestTimeEn: 'Morning & Evening', 
    note: 'Chuẩn vị bánh canh cá lóc xứ Huế, sợi bánh canh dai mềm hòa quyện nước dùng đậm đà.', 
    noteEn: 'Authentic Hue-style thick noodle soup with tender snakehead fish and rich savory broth.' 
  },
  { 
    name: 'Bánh Canh Ghẹ 88', 
    nameEn: '88 Crab Thick Noodles', 
    lat: 20.2528, 
    lng: 105.9695, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Ngõ 214 Tây Thành, Tân Thành, Ninh Bình', 
    locationEn: 'Alley 214 Tay Thanh Street, Tan Thanh, Ninh Binh', 
    price: '40.000 – 70.000đ/bát', 
    priceEn: '40,000 – 70,000 VND/bowl', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Bánh canh ghẹ hải sản nước dùng sánh đặc ngọt thanh từ ghẹ tươi, không gian quán sạch sẽ.', 
    noteEn: 'Thick noodle soup with fresh crab, rich and sweet seafood broth, clean dining area.' 
  },
  { 
    name: 'Phở An', 
    nameEn: 'An Traditional Pho', 
    lat: 20.2482, 
    lng: 105.9752, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '14 Ngõ 862 Đường Trần Hưng Đạo, Ninh Bình', 
    locationEn: '14 Alley 862 Tran Hung Dao Street, Ninh Binh', 
    price: '35.000 – 50.000đ/bát', 
    priceEn: '35,000 – 50,000 VND/bowl', 
    bestTime: 'Buổi sáng', 
    bestTimeEn: 'Morning', 
    note: 'Quán phở bò, phở gà gia truyền núp hẻm nhưng rất đông khách địa phương nhờ nước dùng thanh ngọt.', 
    noteEn: 'Traditional beef and chicken Pho hidden in an alley, highly popular among locals for its sweet broth.' 
  },
  { 
    name: 'Miến Lươn Bà Phấn', 
    nameEn: 'Ba Phan Eel Noodles', 
    lat: 20.2595, 
    lng: 105.9712, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '995 Trần Hưng Đạo, Thanh Bình, Ninh Bình', 
    locationEn: '995 Tran Hung Dao Street, Thanh Binh, Ninh Binh', 
    price: '30.000 – 50.000đ/bát', 
    priceEn: '30,000 – 50,000 VND/bowl', 
    bestTime: 'Buổi sáng (6h–10h)', 
    bestTimeEn: 'Morning only (6–10am)', 
    note: 'Đặc sản miến lươn cố đô nổi tiếng bậc nhất, nước dùng đậm đà, thịt lươn rim khô thơm lừng không tanh.', 
    noteEn: 'Famous local specialty eel noodle soup, savory broth with well-seasoned dried eel, no gamey smell.' 
  },
  { 
    name: 'Phở Gà Phố Cổ', 
    nameEn: 'Pho Ga Pho Co', 
    lat: 20.2635, 
    lng: 105.9750, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '2/80 Đường Tràng An, Tân Thành, Hoa Lư, Ninh Bình', 
    locationEn: '2/80 Trang An Street, Tan Thanh, Hoa Lu, Ninh Binh', 
    price: '35.000 – 60.000đ/bát', 
    priceEn: '35,000 – 60,000 VND/bowl', 
    bestTime: 'Buổi sáng', 
    bestTimeEn: 'Morning', 
    note: 'Nằm ngay gần khu Phố cổ, chuyên phở gà ta thịt chắc béo ngậy, nước dùng thanh vị sả gừng.', 
    noteEn: 'Located near the Old Quarter, specializing in free-range chicken Pho with clear ginger-infused broth.' 
  },
  { 
    name: 'Bún Bò Huế 330 Xuân Thành', 
    nameEn: '330 Xuan Thanh Hue Beef Noodles', 
    lat: 20.2512, 
    lng: 105.9678, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '330 Đường Xuân Thành, Tân Thành, Ninh Bình', 
    locationEn: '330 Xuan Thành Street, Tan Thanh, Ninh Binh', 
    price: '40.000 – 60.000đ/bát', 
    priceEn: '40,000 – 60,000 VND/bowl', 
    bestTime: 'Sáng & Tối', 
    bestTimeEn: 'Morning & Evening', 
    note: 'Tô bún bò huế đầy đặn, nước dùng đậm đà hương mắm ruốc chuẩn vị miền Trung.', 
    noteEn: 'Generous bowl of Hue beef noodles featuring a rich broth infused with authentic lemongrass and shrimp paste.' 
  },
  { 
    name: 'Bún Bò Huế 148', 
    nameEn: '148 Hue Beef Noodles', 
    lat: 20.2495, 
    lng: 105.9682, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '148 Đường Xuân Thành, Tân Thành, Ninh Bình', 
    locationEn: '148 Xuan Thanh Street, Tan Thanh, Ninh Binh', 
    price: '40.000 – 65.000đ/bát', 
    priceEn: '40,000 – 65,000 VND/bowl', 
    bestTime: 'Buổi sáng (5h–13h)', 
    bestTimeEn: 'Morning (5am–1pm)', 
    note: 'Topping phong phú từ bò nạm, chả cua, tiết, móng giò, nước dùng ngọt tự nhiên từ xương hầm.', 
    noteEn: 'Rich toppings including beef shank, crab patties, blood pudding, pork trotters; naturally sweet bone broth.' 
  },
  { 
    name: 'Bún Thang Phở Gà Thái', 
    nameEn: 'Thai Noodle Soup & Chicken Pho', 
    lat: 20.2558, 
    lng: 105.9702, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '48 Đường Phúc Thành, Phúc Thành, Ninh Bình', 
    locationEn: '48 Phuc Thanh Street, Phuc Thanh, Ninh Binh', 
    price: '35.000 – 50.000đ/bát', 
    priceEn: '35,000 – 50,000 VND/bowl', 
    bestTime: 'Buổi sáng', 
    bestTimeEn: 'Morning', 
    note: 'Chuyên bún thang Hà Nội và phở gà ta, các nguyên liệu thái chỉ cầu kỳ, nước dùng trong vắt.', 
    noteEn: 'Specializing in Hanoi-style Bun Thang and chicken Pho with delicate shredded toppings and clear broth.' 
  },
  { 
    name: 'Bún Cá Chấm Khu 9', 
    nameEn: 'Khu 9 Crispy Fish Noodles', 
    lat: 20.2546, 
    lng: 105.9752, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '134 Đường Lương Văn Thăng, Đông Thành, Ninh Bình', 
    locationEn: '134 Luong Van Thang Street, Dong Thanh, Ninh Binh', 
    price: '35.000 – 50.000đ/suất', 
    priceEn: '35,000 – 50,000 VND/portion', 
    bestTime: 'Sáng & Trưa', 
    bestTimeEn: 'Morning & Lunch', 
    note: 'Mô hình bún cá chấm độc đáo, cá chiên giòn rụm bên ngoài mọng nước bên trong ăn kèm nước mắm tỏi ớt.', 
    noteEn: 'Unique dipping fish noodles, deep-fried crispy fish served with a savory garlic-chili dipping sauce.' 
  },
  { 
    name: 'Cù Kỳ Quán (Bún Hải Sản & Lẩu)', 
    nameEn: 'Cu Ky Seafood Noodles & Hotpot', 
    lat: 20.2580, 
    lng: 105.9660, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '59 Đường Đinh Điền, Đông Thành, Ninh Bình', 
    locationEn: '59 Dinh Dien Street, Dong Thanh, Ninh Binh', 
    price: '40.000đ/bát bún - 150.000đ/người lẩu', 
    priceEn: '40,000 VND/bowl - 150,000 VND/person for hotpot', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Nổi tiếng với bún hải sản ngọt nước buổi sáng và các set lẩu hải sản bình dân, tươi ngon vào buổi tối.', 
    noteEn: 'Famous for sweet seafood noodles in the morning and budget-friendly, fresh seafood hotpots in the evening.' 
  },
  { 
    name: 'Bún Hải Sản Đại Anh', 
    nameEn: 'Dai Anh Seafood Noodles', 
    lat: 20.2530, 
    lng: 105.9690, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '1 Tây Thành, Tân Thành, Ninh Bình', 
    locationEn: '1 Tay Thanh Street, Tan Thanh, Ninh Binh', 
    price: '40.000 – 60.000đ/bát', 
    priceEn: '40,000 – 60,000 VND/bowl', 
    bestTime: 'Buổi sáng', 
    bestTimeEn: 'Morning', 
    note: 'Bát bún đầy đặn nhiều hải sản tươi gồm tôm, mực, bề bề, nước dùng chua cay kích thích vị giác.', 
    noteEn: 'Hearty noodles packed with fresh seafood like shrimp, squid, and mantis shrimp in a spicy sour broth.' 
  },
  { 
    name: 'Bún Cá Chấm An Viên', 
    nameEn: 'An Vien Dipping Fish Noodles', 
    lat: 20.2524, 
    lng: 105.9742, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '8 Phạm Hồng Thái, Vân Giang, Ninh Bình', 
    locationEn: '8 Pham Hong Thai Street, Van Giang, Ninh Binh', 
    price: '35.000 – 50.000đ/suất', 
    priceEn: '35,000 – 50,000 VND/portion', 
    bestTime: 'Sáng & Trưa', 
    bestTimeEn: 'Morning & Lunch', 
    note: 'Cá rô phi phi lê chiên vàng ruộm, nước chấm pha rất khéo kết hợp bún sợi nhỏ mướt.', 
    noteEn: 'Crispy deep-fried tilapias served with masterfully mixed dipping sauce and fine rice noodles.' 
  },
  { 
    name: 'Lẩu Hải Âu', 
    nameEn: 'Hai Au Hotpot', 
    lat: 20.25538, 
    lng: 105.96317, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '132 Đường Lê Thái Tổ, Phường Hoa Lư, Ninh Bình', 
    locationEn: '132 Le Thai To Street, Hoa Lu Ward, Ninh Binh', 
    price: '150.000 – 300.000đ/người', 
    priceEn: '150,000 – 300,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán lẩu bình dân quen thuộc của người địa phương, không gian rộng rãi.', 
    noteEn: 'A popular budget-friendly hotpot spot for locals, spacious seating.' 
  },
  { 
    name: 'Nướng Dũng Ấm', 
    nameEn: 'Dung Am BBQ', 
    lat: 20.26640, 
    lng: 105.97581, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '34 Đường Đào Duy Từ, Phường Hoa Lư, Ninh Bình', 
    locationEn: '34 Dao Duy Tu Street, Hoa Lu Ward, Ninh Binh', 
    price: '150.000 – 250.000đ/người', 
    priceEn: '150,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán nướng vỉa hè ngon có tiếng, tẩm ướp đậm đà, đồ ăn tươi.', 
    noteEn: 'Famous street BBQ shop with well-marinated fresh ingredients.' 
  },
  { 
    name: 'Ăn Rồi Lăn — Bò Nướng Than Hoa', 
    nameEn: 'An Roi Lan — Charcoal Grilled Beef & Hotpot', 
    lat: 20.25470, 
    lng: 105.96635, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '01 Đường Tây Thành, Phố Phúc Nam, Phường Phúc Thành, Ninh Bình', 
    locationEn: '01 Tay Thanh Street, Phuc Thanh Ward, Ninh Binh', 
    price: '120.000 – 250.000đ/người', 
    priceEn: '120,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Chuyên bò nướng than hoa thơm phức và các set lẩu giá sinh viên.', 
    noteEn: 'Specializing in fragrant charcoal-grilled beef and student-friendly hotpots.' 
  },
  { 
    name: 'Bò Bản Mộc (Gần Quảng Trường)', 
    nameEn: 'Bo Ban Moc Restaurant', 
    lat: 20.27400, 
    lng: 105.97451, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Đường Tôn Đức Thắng, Phường Đông Thành, Ninh Bình', 
    locationEn: 'Ton Duc Thang Street, Dong Thành Ward, Ninh Binh', 
    price: '150.000 – 300.000đ/người', 
    priceEn: '150,000 – 300,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Không gian nhà sàn mộc mạc, chuyên các món từ bò tơ tươi ngon, gần quảng trường Đinh Tiên Hoàng.', 
    noteEn: 'Rustic stilt-house design, specializing in fresh veal dishes, near Dinh Tien Hoang Square.' 
  },
  { 
    name: 'Lẩu Sườn Bò Kim Chi Chang Chang', 
    nameEn: 'Chang Chang Beef Rib Kimchi Hotpot', 
    lat: 20.26232, 
    lng: 105.98002, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Ngõ 50 Đường Ngô Quyền, Phường Đông Thành, Ninh Bình', 
    locationEn: 'Alley 50 Ngo Quyen Street, Dong Thanh Ward, Ninh Binh', 
    price: '100.000 – 200.000đ/người', 
    priceEn: '100,000 – 200,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Vị lẩu kim chi chua cay đậm đà kết hợp sườn bò hầm mềm. Điểm tụ tập hot của giới trẻ.', 
    noteEn: 'Spicy and sour kimchi broth with tender braised beef ribs. A popular gathering spot for youth.' 
  },
  { 
    name: 'Lẩu Nướng Bà Nga', 
    nameEn: 'Ba Nga BBQ & Hotpot', 
    lat: 20.25544, 
    lng: 105.96327, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '122 Đường Lê Thái Tổ, Phường Hoa Lư, Ninh Bình', 
    locationEn: '122 Le Thai To Street, Hoa Lu Ward, Ninh Binh', 
    price: '150.000 – 250.000đ/người', 
    priceEn: '150,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán ăn đêm bình dân, phục vụ nhanh, menu lẩu nướng đa dạng đồ đồng quê và hải sản.', 
    noteEn: 'Budget late-night diner, fast service, diverse menu from country meats to seafood.' 
  },
  { 
    name: 'Gogi House (Đinh Tiên Hoàng)', 
    nameEn: 'Gogi House Korean BBQ', 
    lat: 20.26387, 
    lng: 105.97542, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Tầng 2, 219 Đường Lương Văn Thăng, Phường Đông Thành, Ninh Bình', 
    locationEn: '2nd Floor, 219 Luong Van Thang Street, Dong Thanh Ward, Ninh Binh', 
    price: '300.000 – 450.000đ/người', 
    priceEn: '300,000 – 450,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Thương hiệu nướng buffet chuẩn Hàn Quốc cao cấp, máy lạnh mát mẻ, phục vụ chu đáo.', 
    noteEn: 'Premium Korean BBQ buffet chain, air-conditioned, professional service.' 
  },
  { 
    name: 'Nướng Mậu Dịch (Phố Cổ)', 
    nameEn: 'Mau Dich Vintage BBQ', 
    lat: 20.26276, 
    lng: 105.96547, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Đường Tràng An 2, Tân Thành, Đông Thành, Ninh Bình', 
    locationEn: 'Trang An 2 Street, Dong Thanh Ward, Ninh Binh', 
    price: '150.000 – 250.000đ/người', 
    priceEn: '150,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Không gian decor phong cách thời bao cấp độc lạ, đồ nướng tẩm ướp ngon, nằm sát Phố cổ Hoa Lư.', 
    noteEn: 'Unique subsidy-era vintage decor, well-seasoned BBQ, located right by Hoa Lu Old Quarter.' 
  },
  { 
    name: 'Mộc An Quán', 
    nameEn: 'Moc An Quán', 
    lat: 20.26318, 
    lng: 105.96663, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Đường Tràng An 2, Phường Tân Thành, Ninh Bình', 
    locationEn: 'Trang An 2 Street, Tan Thanh Ward, Ninh Binh', 
    price: '120.000 – 250.000đ', 
    priceEn: '120,000 – 250,000 VND', 
    bestTime: 'Chiều & Đêm', 
    bestTimeEn: 'Afternoon & Night', 
    note: 'Quán nhậu đồ nướng lẩu bình dân, thích hợp cho nhóm bạn lai rai đêm muộn gần khu Phố cổ.', 
    noteEn: 'Budget casual BBQ & hotpot pub, perfect for late-night gatherings near the Old Quarter.' 
  },
  { 
    name: 'Lẩu Nướng Hà Linh (Hà Phố Cổ)', 
    nameEn: 'Ha Linh BBQ & Hotpot', 
    lat: 20.26317, 
    lng: 105.96643, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Ngõ 12/14 Đường Thành Công, Phường Tân Thành, Ninh Bình', 
    locationEn: 'Alley 12/14 Thanh Cong Street, Tan Thanh Ward, Ninh Binh', 
    price: '100.000 – 200.000đ/người', 
    priceEn: '100,000 – 200,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán lẩu nướng vỉa hè bình dân ngay khu vực sầm uất gần Phố cổ Hoa Lư.', 
    noteEn: 'Budget street food style BBQ and hotpot situated near the bustling Old Quarter area.' 
  },
  { 
    name: 'SAM SIK — Nhà hàng Hàn Quốc', 
    nameEn: 'Sam Sik Korean Restaurant', 
    lat: 20.27866, 
    lng: 105.95716, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Số 80-82 Phố Bình Khang, Phường Ninh Khánh, Ninh Bình', 
    locationEn: '80-82 Binh Khang Street, Ninh Khanh Ward, Ninh Binh', 
    price: '150.000 – 300.000đ/người', 
    priceEn: '150,000 – 300,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Quán ăn do chủ người Hàn đứng bếp, chuẩn vị kim chi, thịt nướng, canh sườn bò.', 
    noteEn: 'Authentic Korean restaurant run by a Korean chef, offering great grilled meats and soups.' 
  },
  { 
    name: 'Kumzandi (금잔디 식당)', 
    nameEn: 'Kumzandi Korean Dining', 
    lat: 20.26440, 
    lng: 105.96131, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '111 Đường Lê Thái Tổ, Phường Tân Thành, Ninh Bình', 
    locationEn: '111 Le Thai To Street, Tan Thanh Ward, Ninh Binh', 
    price: '200.000 – 400.000đ/người', 
    priceEn: '200,000 – 400,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Nhà hàng Hàn Quốc cao cấp, không gian sang trọng yên tĩnh, chuyên tiếp khách và khách đoàn.', 
    noteEn: 'Premium Korean restaurant, upscale and quiet atmosphere, ideal for business dining.' 
  },
  { 
    name: 'Eumju Grill Restaurant', 
    nameEn: 'Eumju Grill Restaurant', 
    lat: 20.26346, 
    lng: 105.96213, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '108 Đường Tràng An, Phường Tân Thành, Ninh Bình', 
    locationEn: '108 Trang An Street, Tan Thanh Ward, Ninh Binh', 
    price: '200.000 – 350.000đ/người', 
    priceEn: '200,000 – 350,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán thịt nướng kiểu Hàn Quốc hiện đại nằm ngay trục đường chính đi Tràng An, view đẹp.', 
    noteEn: 'Modern Korean BBQ restaurant located on the main road to Trang An, nice view.' 
  },
  { 
    name: 'Gasu BBQ', 
    nameEn: 'Gasu BBQ & Hotpot', 
    lat: 20.26810, 
    lng: 105.97026, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '181 Đường Đông Phương Hồng, Phường Đông Thành, Ninh Bình', 
    locationEn: '181 Dong Phuong Hong Street, Dong Thanh Ward, Ninh Binh', 
    price: '150.000 – 300.000đ/người', 
    priceEn: '150,000 – 300,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Mô hình kết hợp nướng lẩu không khói và lẩu hấp thủy nhiệt hải sản tươi sống rất độc đáo.', 
    noteEn: 'Unique combo of smokeless BBQ and fresh seafood steam hotpot.' 
  },
  { 
    name: 'XingFu 幸福 1998 — Dimsum & Lẩu', 
    nameEn: 'XingFu 1998 — Dimsum & Hotpot', 
    lat: 20.24972, 
    lng: 105.95969, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '91 Đường Lê Thánh Tông (Mặt kênh Đô Thiên), Phường Hoa Lư, Ninh Bình', 
    locationEn: '91 Le Thanh Tong Street, Hoa Lu Ward, Ninh Binh', 
    price: '100.000 – 250.000đ/người', 
    priceEn: '100,000 – 250,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Chuyên Dimsum Trung Hoa (há cảo, xíu mại) và lẩu móng rồng thơm ngon, không gian decor xinh xắn.', 
    noteEn: 'Specializing in Chinese Dimsum and delicious hotpot with cute Instagrammable decor.' 
  },
  { 
    name: 'Việt Tộp Quán', 
    nameEn: 'Viet Top Quán', 
    lat: 20.25649, 
    lng: 105.96068, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '245 Đường Cát Linh, Phường Tân Thành, Ninh Bình', 
    locationEn: '245 Cat Linh Street, Tan Thanh Ward, Ninh Binh', 
    price: '150.000 – 250.000đ/người', 
    priceEn: '150,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán nhậu đồ nướng, hải sản tươi và các món lẩu đồng quê thơm ngon, không gian mở thoáng đãng.', 
    noteEn: 'Casual open-air pub offering grilled meats, fresh seafood, and tasty countryside hotpots.' 
  },
  { 
    name: 'Chạm — Buffet Lẩu Nướng', 
    nameEn: 'Cham — BBQ & Hotpot Buffet', 
    lat: 20.25203, 
    lng: 105.96340, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '343 Đường Lê Thái Tổ, Phường Tân Thành, Ninh Bình', 
    locationEn: '343 Le Thai To Street, Tan Thanh Ward, Ninh Binh', 
    price: '199.000 – 299.000đ/người', 
    priceEn: '199,000 – 299,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Nhà hàng buffet lẩu nướng không khói rất hot tại Ninh Bình, đồ ăn quầy line phong phú, có máy lạnh.', 
    noteEn: 'Very trendy smokeless BBQ & hotpot buffet in town, rich food lines, fully air-conditioned.' 
  },
  { 
    name: 'Panda Buffet Lẩu Nướng', 
    nameEn: 'Panda BBQ Buffet', 
    lat: 20.26360, 
    lng: 105.96268, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '86 Đường Tràng An, Phường Tân Thành, Ninh Bình', 
    locationEn: '86 Trang An Street, Tan Thanh Ward, Ninh Binh', 
    price: '150.000 – 250.000đ/người', 
    priceEn: '150,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Buffet giá bình dân nằm ngay đối diện khu vực Phố cổ Hoa Lư, cực kỳ tiện lợi cho khách du lịch ăn tối.', 
    noteEn: 'Budget-friendly buffet located right opposite Hoa Lu Old Quarter, super convenient for tourists.' 
  },
  { 
    name: 'Urban BBQ — Lẩu Sườn Bò Kim Chi', 
    nameEn: 'Urban BBQ Restaurant', 
    lat: 20.27346, 
    lng: 105.95860, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Khu Đô Thị Xuân Thành, Phường Ninh Khánh, Ninh Bình', 
    locationEn: 'Xuan Thanh Urban Area, Ninh Khanh Ward, Ninh Binh', 
    price: '150.000 – 300.000đ/người', 
    priceEn: '150,000 – 300,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Nằm trong khu đô thị mới, không gian hiện đại, nổi tiếng với món lẩu sườn bò kim chi chuẩn vị.', 
    noteEn: 'Located in the new urban area, modern space, famous for its authentic beef rib kimchi hotpot.' 
  },
  { 
    name: 'InCheon Lẩu Nướng', 
    nameEn: 'InCheon BBQ & Hotpot', 
    lat: 20.27561, 
    lng: 105.96509, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '20 Đường Hoàng Quốc Việt, Phường Ninh Khánh, Ninh Bình', 
    locationEn: '20 Hoang Quoc Viet Street, Ninh Khanh Ward, Ninh Binh', 
    price: '150.000 – 250.000đ/người', 
    priceEn: '150,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Nhà hàng lẩu nướng mang phong cách Hàn Quốc, quầy line đầy đặn, chỗ đậu xe ô tô thoải mái.', 
    noteEn: 'Korean-style BBQ restaurant with a full food line and spacious car parking.' 
  },
  { 
    name: '1988 — BBQ Buffet Lẩu Nướng', 
    nameEn: '1988 — BBQ & Hotpot Buffet', 
    lat: 20.25056, 
    lng: 105.95922, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '11 Đường Lê Thánh Tông, Phường Hoa Lư, Ninh Bình', 
    locationEn: '11 Le Thanh Tong Street, Hoa Lu Ward, Ninh Binh', 
    price: '150.000 – 250.000đ/người', 
    priceEn: '150,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Không gian buffet lẩu nướng rộng rãi, thực đơn quầy line đa dạng món ăn kèm đồ chiên ngon miệng.', 
    noteEn: 'Spacious BBQ & hotpot buffet, diverse line counter with delicious fried side dishes.' 
  },
  { 
    name: 'BẾP NHÀ MÌNH — Buffet Lẩu & Nướng', 
    nameEn: 'Bep Nha Minh — BBQ & Hotpot', 
    lat: 20.25702, 
    lng: 105.96210, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '286 Đường Cát Linh, Phường Tân Thành, Ninh Bình', 
    locationEn: '286 Cat Linh Street, Tan Thanh Ward, Ninh Binh', 
    price: '139.000 – 219.000đ/người', 
    priceEn: '139,000 – 219,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán lẩu nướng bình dân có tiếng với giới trẻ, không gian mở, phục vụ nhiệt tình chu đáo.', 
    noteEn: 'Popular budget BBQ spot for local youth, features open-air space and attentive staff.' 
  },
  { 
    name: 'Hẻm Lẩu Nướng (Hotpot & BBQ)', 
    nameEn: 'Hem Lau Nuong — Hotpot & BBQ', 
    lat: 20.25368, 
    lng: 105.96541, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Ngõ 31 Đường Tây Thành, Phường Tân Thành, Ninh Bình', 
    locationEn: 'Alley 31 Tay Thanh Street, Tan Thanh Ward, Ninh Binh', 
    price: '100.000 – 180.000đ/người', 
    priceEn: '100,000 – 180,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Nằm trong hẻm nhỏ nhưng cực kỳ đông khách, chuyên các set lẩu nướng vỉa hè giá sinh viên.', 
    noteEn: 'Hidden in a small alley but very crowded, specializing in student-budget street BBQ sets.' 
  },
  { 
    name: 'Việt Linh BBQ', 
    nameEn: 'Viet Linh BBQ', 
    lat: 20.25412, 
    lng: 105.96280, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '158 Đường Lê Thái Tổ, Phường Tân Thành, Ninh Bình', 
    locationEn: '158 Le Thai To Street, Tan Thanh Ward, Ninh Binh', 
    price: '120.000 – 200.000đ/người', 
    priceEn: '120,000 – 200,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán đồ nướng ngói và nướng vỉ truyền thống, đồ ăn ướp đậm đà, nước sốt chấm đặc trưng.', 
    noteEn: 'Traditional tile-grilled and wire-grilled BBQ shop with flavorful marinades and signature sauces.' 
  },
   { 
    name: '168 QUÁN BIA — LẨU — NƯỚNG BBQ', 
    nameEn: '168 Beer, Hotpot & BBQ', 
    lat: 20.25540, 
    lng: 105.96345, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '116 Đường Lê Thái Tổ, Phường Hoa Lư, Ninh Bình', 
    locationEn: '116 Le Thai To Street, Hoa Lu Ward, Ninh Binh', 
    price: '100.000 – 200.000đ/người', 
    priceEn: '100,000 – 200,000 VND/person', 
    bestTime: 'Chiều & Tối', 
    bestTimeEn: 'Afternoon & Evening', 
    note: 'Không gian quán nhậu bình dân rộng rãi, vừa uống bia hơi vừa lai rai lẩu nướng hải sản, đồ đồng quê.', 
    noteEn: 'Spacious local pub style, perfect for fresh draft beer with casual seafood or countryside hotpot.' 
  },
  { 
    name: 'Nướng Mập Kòi', 
    nameEn: 'Map Koi BBQ', 
    lat: 20.26250, 
    lng: 105.96490, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Đường Tràng An 2 (Khu vực Phố Cổ), Phường Tân Thành, Ninh Bình', 
    locationEn: 'Trang An 2 Street (Old Quarter Area), Tan Thanh Ward, Ninh Binh', 
    price: '120.000 – 220.000đ/người', 
    priceEn: '120,000 – 220,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán nướng vỉa hè nằm sát cạnh Phố cổ Hoa Lư, gió mát, thực đơn các món bò và nầm nướng rất chạy.', 
    noteEn: 'Street BBQ spot located right by Hoa Lu Old Quarter, airy space, famous for grilled beef and pork udders.' 
  },
  { 
    name: 'Lẩu Nướng 1999', 
    nameEn: '1999 BBQ & Hotpot', 
    lat: 20.25633, 
    lng: 105.96603, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '183 Đường Tây Thành, Phường Hoa Lư, Ninh Bình', 
    locationEn: '183 Tay Thanh Street, Hoa Lu Ward, Ninh Binh', 
    price: '120.000 – 200.000đ/người', 
    priceEn: '120,000 – 200,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Phục vụ các set combo lẩu nướng tiện lợi, thịt ba chỉ bò và hải sản tươi ướp sốt cay ngọt vị đậm đà.', 
    noteEn: 'Serving convenient BBQ and hotpot combo sets, featuring fresh beef belly and seafood in sweet-spicy sauce.' 
  },
  { 
    name: 'Lẩu Nướng Phủi', 
    nameEn: 'Phui BBQ & Hotpot', 
    lat: 20.24667, 
    lng: 105.98466, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '9 Ngõ 384 Đường Nguyễn Công Trứ, Phường Thanh Bình, Ninh Bình', 
    locationEn: '9 Alley 384 Nguyen Cong Tru Street, Thanh Binh Ward, Ninh Binh', 
    price: '120.000 – 250.000đ/người', 
    priceEn: '120,000 – 250,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Phong cách bụi bặm, "phủi" đúng nghĩa, đồ ăn đầy đặn, giá rẻ, tụ điểm quen thuộc của học sinh sinh viên.', 
    noteEn: 'Street-style design, generous portions at low prices, a very familiar gathering spot for local students.' 
  },
  { 
    name: 'Lẩu Cuốn Huế', 
    nameEn: 'Hue Rolled Hotpot', 
    lat: 20.25526, 
    lng: 105.96621, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '145 Đường Lương Văn Tụy, Phường Tân Thành, Ninh Bình', 
    locationEn: '145 Luong Van Tuy Street, Tan Thanh Ward, Ninh Binh', 
    price: '100.000 – 180.000đ/người', 
    priceEn: '100,000 – 180,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Món lẩu tự cuốn với bánh tráng độc đáo kèm thịt luộc, chả ram, rau sống tươi ngon chuẩn vị miền Trung.', 
    noteEn: 'Unique DIY rice paper rolls served with boiled pork, fried rams, and fresh herbs in Central-style flavor.' 
  },
 { 
    name: 'Lẩu Tuyết', 
    nameEn: 'Tuyet Hotpot Restaurant', 
    lat: 20.26555, 
    lng: 105.96399, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '38 Đường Tân An, Phường Tân Thành, Ninh Bình', 
    locationEn: '38 Tan An Street, Tan Thanh Ward, Ninh Binh', 
    price: '150.000 – 300.000đ/người', 
    priceEn: '150,000 – 300,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Nổi tiếng lâu năm với các món lẩu gà dưỡng sinh, lẩu đuôi bò hầm thuốc bắc bổ dưỡng, vị ngọt thanh.', 
    noteEn: 'Long-standing spot famous for healthy chicken hotpot and herbal stewed beef tail hotpot.' 
  },
 { 
    name: 'Nướng Chảo Gang — Đại Lâm Mộc', 
    nameEn: 'Dai Lam Moc — Cast Iron Skillet BBQ', 
    lat: 20.24781, 
    lng: 105.98520, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: 'Số 30 Ngõ 259 Đường Nguyễn Công Trứ, Phường Thanh Bình, Ninh Bình', 
    locationEn: 'No. 30, Alley 259 Nguyen Cong Tru Street, Thanh Binh Ward, Ninh Binh', 
    price: '120.000 – 200.000đ/người', 
    priceEn: '120,000 – 200,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Hình thức nướng bơ trên chảo gang lót giấy bạc giúp giữ nhiệt tốt, thịt bò mềm và thơm ngậy.', 
    noteEn: 'Butter BBQ on foil-lined cast iron skillets that retains heat well, keeping beef tender and juicy.' 
  },
  { 
    name: 'Quán A! Đây Rồi! 141 Lương Văn Tụy', 
    nameEn: 'A! Day Roi! Restaurant', 
    lat: 20.25390, 
    lng: 105.97155, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '141 Đường Lương Văn Tụy, Phường Tân Thành, Ninh Bình', 
    locationEn: '141 Luong Van Tuy Street, Tan Thanh Ward, Ninh Binh', 
    price: '100.000 – 250.000đ/người', 
    priceEn: '100,000 – 250,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Quán ăn gia đình ấm cúng, nổi tiếng với lẩu riêu cua sườn sụn bắp bò dạt dào topping siêu chất lượng.', 
    noteEn: 'Cozy family restaurant, famous for its high-quality crab paste hotpot with beef shank and pork ribs.' 
  },
  { 
    name: 'Lẩu Nướng Quang Râu', 
    nameEn: 'Quang Rau BBQ & Hotpot', 
    lat: 20.24951, 
    lng: 105.97959, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '169 Đường Nguyễn Văn Cừ, Phường Nam Bình, Ninh Bình', 
    locationEn: '169 Nguyen Van Cu Street, Nam Binh Ward, Ninh Binh', 
    price: '120.000 – 220.000đ/người', 
    priceEn: '120,000 – 220,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Quán lẩu nướng bình dân rộng rãi, phục vụ nhanh nhẹn, thịt nướng tẩm mật ong thơm lừng, mở cửa đến tận đêm muộn.', 
    noteEn: 'Spacious budget BBQ & hotpot spot, fast service, featuring aromatic honey-marinated grilled meats and open until late night.' 
  },
  { 
    name: 'Lẩu Nướng Seoul — 80 Lê Thái Tổ', 
    nameEn: 'Seoul BBQ — 80 Le Thai To', 
    lat: 20.25685, 
    lng: 105.96310, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '80 Đường Lê Thái Tổ, Phường Hoa Lư, Ninh Bình', 
    locationEn: '80 Le Thai To Street, Hoa Lu Ward, Ninh Binh', 
    price: '180.000 – 300.000đ/người', 
    priceEn: '180,000 – 300,000 VND/person', 
    bestTime: 'Buổi tối', 
    bestTimeEn: 'Evening', 
    note: 'Nhà hàng lẩu nướng không khói hương vị Hàn Quốc nằm ngay mặt đường lớn Lê Thái Tổ, chỗ đỗ xe thoải mái.', 
    noteEn: 'Smokeless Korean-style BBQ restaurant on the main Le Thai To street with hassle-free parking.' 
  },
  { 
    name: 'Thanh Phong — Lẩu Bò Tươi Triều Châu', 
    nameEn: 'Thanh Phong — Chaozhou Fresh Beef Hotpot', 
    lat: 20.25552, 
    lng: 105.98188, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '61 Đường Đinh Điền, Phố 12, Phường Đông Thành, Ninh Bình', 
    locationEn: '61 Dinh Dien Street, Ward 12, Dong Thanh Ward, Ninh Binh', 
    price: '150.000 – 350.000đ/người', 
    priceEn: '150,000 – 350,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Chuyên thịt bò tươi cắt nhúng tại bàn theo kiểu Triều Châu, nước lẩu hầm từ xương ống bò ngọt lịm tự nhiên.', 
    noteEn: 'Specializing in Chaozhou-style freshly sliced beef hotpot with naturally sweet bone broth.' 
  },
  { 
    name: 'Đồ Nhật SHIZEN SUSHI NINH BÌNH', 
    nameEn: 'Shizen Sushi Ninh Binh', 
    lat: 20.25292, 
    lng: 105.98315, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '80 Đường Đinh Tiên Hoàng, Phường Đông Thành, Ninh Bình', 
    locationEn: '80 Dinh Tien Hoang Street, Dong Thanh Ward, Ninh Binh', 
    price: '200.000 – 450.000đ/người', 
    priceEn: '200,000 – 450,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Nhà hàng Nhật Bản cao cấp, sashimi tươi rói, sushi đa dạng cuộn khéo léo, không gian ấm cúng sang trọng.', 
    noteEn: 'Premium Japanese dining, super fresh sashimi, skillfully rolled sushi, elegant and cozy atmosphere.' 
  },
  { 
    name: 'TOKYO SUSHI NINH BÌNH', 
    nameEn: 'Tokyo Sushi Ninh Binh', 
    lat: 20.25208, 
    lng: 105.97545, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '253 Đường Trần Hưng Đạo, Phường Đông Thành, Ninh Bình', 
    locationEn: '253 Tran Hung Dao Street, Dong Thanh Ward, Ninh Binh', 
    price: '150.000 – 350.000đ/người', 
    priceEn: '150,000 – 350,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Quán ăn Nhật Bản được giới trẻ địa phương ưa chuộng nhờ các set sushi, cơm lươn giá cả cực kỳ hợp lý.', 
    noteEn: 'Highly favored Japanese restaurant among locals for its reasonably priced sushi sets and eel rice bowls.' 
  },
  { 
    name: 'Đồ Thái — NarCi Thai', 
    nameEn: 'NarCi Thai — Authentic Thai Cuisine', 
    lat: 20.26426, 
    lng: 105.97790, 
    color: '#f59e0b', 
    type: 'food', 
    priority: true, 
    location: '298 Đường Lương Văn Thăng, Phường Đông Thành, Ninh Bình', 
    locationEn: '298 Luong Van Thang Street, Dong Thanh Ward, Ninh Binh', 
    price: '150.000 – 300.000đ/người', 
    priceEn: '150,000 – 300,000 VND/person', 
    bestTime: 'Trưa & Tối', 
    bestTimeEn: 'Lunch & Dinner', 
    note: 'Chuyên ẩm thực Thái Lan chuẩn vị, nổi bật với gỏi đu đủ ba khía cay nồng và lẩu Thái Tomyum cốt dừa béo ngậy.', 
    noteEn: 'Specializing in authentic Thai cuisine, outstanding spicy papaya salad and creamy coconut Tomyum hotpot.' 
  },
  {
    name: 'Bún Chả Quạt Tuấn Anh',
    nameEn: 'Tuan Anh Grilled Pork Noodles',
    lat: 20.2505,
    lng: 105.9715,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '168 Nam Thành, Tân Thành, Ninh Bình',
    locationEn: '168 Nam Thanh Street, Tan Thành, Ninh Binh',
    price: '40.000 – 60.000đ/suất',
    priceEn: '40,000 – 60,000 VND/portion',
    bestTime: 'Buổi sáng & Trưa',
    bestTimeEn: 'Morning & Lunch time',
    note: 'Quán bún chả quạt gia truyền nổi tiếng với bún lá nén chắc tay, miếng chả to nướng vàng cánh gián dậy mùi đặc trưng Cố đô.',
    noteEn: 'Famous traditional grilled pork noodle shop known for compact rice noodle sheets and large, perfectly smokey pork patties.'
  },
  {
    name: 'Nhà hàng Dê Hoàng Phương 2',
    nameEn: 'Hoang Phuong Goat Restaurant 2',
    lat: 20.2520,
    lng: 105.9695,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '253 Lê Thái Tổ, Tân Thành, Hoa Lư, Ninh Bình',
    locationEn: '253 Le Thai To Street, Tan Thanh, Hoa Lu, Ninh Binh',
    price: '200.000 – 300.000đ/người',
    priceEn: '200,000 – 300,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Nổi tiếng với món lẩu dê đậm đà ninh từ xương và thuốc bắc. Không gian rộng rãi, thoáng mát, nằm gần khu trung tâm du lịch.',
    noteEn: 'Famous for rich goat hotpot simmered from bones and herbs. Spacious, airy setting located near the tourism center.'
  },
  {
    name: 'Bánh Cuốn Nóng Hương Hương',
    nameEn: 'Huong Huong Hot Rice Crepes',
    lat: 20.2635,
    lng: 105.9742,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '52 Ngô Quyền, Đông Thành, Ninh Bình',
    locationEn: '52 Ngo Quyen Street, Dong Thanh, Ninh Binh',
    price: '30.000 – 50.000đ/suất',
    priceEn: '30,000 – 50,000 VND/portion',
    bestTime: 'Buổi sáng',
    bestTimeEn: 'Morning',
    note: 'Bánh cuốn tráng tay nóng hổi, vỏ bánh mỏng mướt thơm mùi gạo, ăn kèm chả mỡ béo ngậy và nước chấm pha khéo.',
    noteEn: 'Freshly hand-rolled hot rice crepes with a smooth, thin texture. Served with savory pork patties and well-balanced dipping sauce.'
  },
  {
    name: 'Tiệm Trộn',
    nameEn: 'Tiem Tron - Mixed Noodles & Snacks',
    lat: 20.2588,
    lng: 105.9712,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Số 8, Ngõ 80, Lê Thánh Tông, Đông Thành, Ninh Bình',
    locationEn: 'No. 8, Alley 80, Le Thanh Tong Street, Dong Thanh, Ninh Binh',
    price: '30.000 – 60.000đ/món',
    priceEn: '30,000 – 60,000 VND/dish',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Địa điểm ăn vặt yêu thích của giới trẻ Ninh Bình với mì trộn, bánh đa trộn đậm vị và các loại trà giải nhiệt.',
    noteEn: 'A favorite snack spot for local youth, famous for flavorful mixed noodles, mixed rice sheets, and refreshing teas.'
  },
  {
    name: 'Bún Chả Ngõ 5',
    nameEn: 'Ngo 5 Grilled Pork Noodles',
    lat: 20.2548,
    lng: 105.9715,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '202 Lê Thái Tổ, Tân Thành, Ninh Bình',
    locationEn: '202 Le Thai To Street, Tan Thanh, Ninh Binh',
    price: '40.000 – 55.000đ/suất',
    priceEn: '40,000 – 55,000 VND/portion',
    bestTime: 'Buổi sáng & Trưa',
    bestTimeEn: 'Morning & Lunch time',
    note: 'Quán bún chả gia truyền có tiếng, thịt nướng thơm phức không bị khô, nước chấm đu đủ xanh chua ngọt vừa vặn.',
    noteEn: 'Well-known traditional grilled pork noodle shop. Juicy grilled pork served with a well-balanced sweet and sour papaya dipping sauce.'
  },
  {
    name: 'Cuốn Út Hân',
    nameEn: 'Ut Han Fresh Rice Rolls',
    lat: 20.2395,
    lng: 105.9922,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '796 Nguyễn Công Trứ, Thanh Bình, Ninh Bình',
    locationEn: '796 Nguyen Cong Tru Street, Thanh Binh, Ninh Binh',
    price: '50.000 – 150.000đ/người',
    priceEn: '50,000 – 150,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Chuyên các món cuốn thanh mát như bánh tráng cuốn thịt heo, tai heo và nem lụi. Đồ ăn kèm rau sống cực kỳ tươi sạch.',
    noteEn: 'Specializing in refreshing Vietnamese rolls like pork belly, pig ears, and lemongrass pork skewers wrapped in rice paper with fresh herbs.'
  },
  {
    name: 'Sisterfields Tam Cốc',
    nameEn: 'Sisterfields Tam Coc',
    lat: 20.2185,
    lng: 105.9252,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Đường Tam Cốc (gần Bến thuyền Tam Cốc), Ninh Hải, Hoa Lư, Ninh Bình',
    locationEn: 'Tam Coc Road (near Tam Coc Wharf), Ninh Hai, Hoa Lu, Ninh Binh',
    price: '80.000 – 200.000đ/người',
    priceEn: '80,000 – 200,000 VND/person',
    bestTime: 'Sáng & Trưa',
    bestTimeEn: 'Morning & Lunch time',
    note: 'Quán cafe & brunch phong cách phương Tây hiện đại, không gian mở thoáng mát. Phục vụ cà phê máy chuẩn vị, sinh tố, bánh ngọt và các món ăn sáng kiểu Úc chất lượng.',
    noteEn: 'Modern Western-style cafe & brunch with an airy open space. Serving specialty coffee, smoothies, pastries, and high-quality Australian-style breakfast.'
  },
  {
    name: 'Pizza Sen (Phố Cổ Hoa Lư)',
    nameEn: 'Pizza Sen (Hoa Lu Old Quarter)',
    lat: 20.2494,
    lng: 105.9764,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Khu gian hàng ẩm thực, Phố cổ Hoa Lư, Ninh Bình',
    locationEn: 'Food Stall Area, Hoa Lu Old Quarter, Ninh Binh',
    price: '100.000 – 250.000đ/người',
    priceEn: '100,000 – 250,000 VND/person',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Thương hiệu Pizza nội địa được ưa chuộng. Vị trí trong lòng Phố cổ giúp bạn vừa thưởng thức pizza đế mỏng giòn, vừa ngắm cảnh phố cổ lung linh về đêm.',
    noteEn: 'A popular local pizza brand. Located inside the Old Quarter, perfect for enjoying thin-crust pizza while admiring the vibrant night view.'
  },
  {
    name: 'Pizza Sen Tam Cốc (Bến Xe Đồng Gừng)',
    nameEn: 'Pizza Sen Tam Coc (Dong Gung Bus Station)',
    lat: 20.2186,
    lng: 105.9242,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Khu vực bến xe Đồng Gừng, Tam Cốc, Ninh Hải, Hoa Lư, Ninh Bình',
    locationEn: 'Dong Gung Bus Station Area, Tam Coc, Ninh Hai, Hoa Lu, Ninh Binh',
    price: '120.000 – 280.000đ/người',
    priceEn: '120,000 – 280,000 VND/person',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Nằm ngay bến xe Đồng Gừng sát bến thuyền Tam Cốc. Không gian mở tiện lợi cho khách du lịch dừng chân nghỉ ngơi và ăn uống sau chuyến chèo thuyền.',
    noteEn: 'Located right at Dong Gung bus station near Tam Coc wharf. Convenient open space for travelers to rest and dine after the boat tour.'
  },
  {
    name: 'Quán Cua Phố Cổ',
    nameEn: 'Old Quarter Crab Restaurant',
    lat: 20.2628,
    lng: 105.9754,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '80/2 Đường Tràng An, Tân Thành, Hoa Lư, Ninh Bình',
    locationEn: '80/2 Trang An Street, Tan Thanh, Hoa Lu, Ninh Binh',
    price: '150.000 – 350.000đ/người',
    priceEn: '150,000 – 350,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Nằm ngay ngõ cạnh Cơm Niêu Việt Xưa CS1 đối diện Phố cổ. Chuyên các món lẩu cua đồng Tây Đô, cua biển, hải sản tươi sống vị đậm đà.',
    noteEn: 'Located in the alley next to Com Nieu Viet Xua CS1, opposite the Old Quarter. Specializing in flavorful field crab hotpot and fresh seafood.'
  },
  {
    name: 'Gà Rán Busan',
    nameEn: 'Busan Fried Chicken',
    lat: 20.2504,
    lng: 105.9763,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '101 Trần Hưng Đạo, Đông Thành, Ninh Bình',
    locationEn: '101 Tran Hung Dao Street, Dong Thanh, Ninh Binh',
    price: '50.000 – 150.000đ/người',
    priceEn: '50,000 – 150,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Quán gà rán phong cách Hàn Quốc nằm trục đường lớn đối diện Phố cổ Hoa Lư. Gà sốt cay ngọt, sốt mật ong giòn rụm, không gian điều hòa mát mẻ.',
    noteEn: 'Korean-style fried chicken restaurant on the main street opposite Hoa Lu Old Quarter. Famous for crispy sweet & spicy or honey-glazed chicken in an AC space.'
  }
];
